#!/bin/bash

emacs -batch -eval "(progn (load \"~/git/org-mode/lisp/org.el\") \
			   (load \"~/git/config/dotemacs.el\") \
                           (R) \
                           (org-publish \"ipsurlatex\") \
                           (org-babel-tangle-file \"IPSUR.org\") \
                           (org-publish \"ipsurhtml\"))"
cd ~/outputlatex
latex IPSUR.tex
bibtex IPSUR
makeindex IPSUR
latex IPSUR.tex
latex IPSUR.tex
dvips IPSUR
gs -dSAFER -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sPAPERSIZE=a4 -dPDFSETTINGS=/printer -dCompatibilityLevel=1.3 -dMaxSubsetPct=100 -dSubsetFonts=true -dEmbedAllFonts=true -sOutputFile=IPSUR.pdf IPSUR.ps

cd ~/git/IPSUR
cp ~/outputlatex/IPSUR.pdf IPSUR.pdf
cp ~/outputlatex/IPSUR.tex IPSUR.tex
cp ~/outputhtml/IPSUR.html IPSUR.html
rm sitemap.org
rm theindex.org
