project:
  type: website
  output-dir: docs

website:
  title: "IPSUR: Introduction to Probability and Statistics Using R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: github
        href: https://github.com/gjkerns
      - icon: mastodon
        href: "https://mathstodon.xyz/@gjkerns"
      - icon: linkedin
        href: https://www.linkedin.com/in/g-jay-kerns-9ab99111/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

