#+STARTUP:   indent
* The Appendix

* \textsf{R} Session Information
\label{cha:R-Session-Information}

If you ever write the \textsf{R} help mailing list with a question, then you should include your session information in the email; it makes the reader's job easier and is requested by the Posting Guide. Here is how to do that, and below is what the output looks like.

#+begin_src R :exports both :results output pp 
sessionInfo()
#+end_src

#+latex: \vfill{}

* GNU Free Documentation License
\label{cha:GNU-Free-Documentation}

#+begin_latex
\begin{center}
\textbf{\large Version 1.3, 3 November 2008}\bigskip{}

\par\end{center}

\noindent Copyright (C) 2000, 2001, 2002, 2007, 2008 Free Software
Foundation, Inc.

\begin{center}
\url{http://fsf.org/}
\par\end{center}
#+end_latex

\noindent Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

** 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional and useful document free  in the sense of freedom: to assure everyone the effective freedom to copy and redistribute it, with or without modifying it, either commercially or noncommercially. Secondarily, this License preserves for the author and publisher a way to get credit for their work, while not being considered responsible for modifications made by others.

This License is a kind of copyleft, which means that derivative works of the document must themselves be free in the same sense. It complements the GNU General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software, because free software needs free documentation: a free program should come with manuals providing the same freedoms that the software does. But this License is not limited to software manuals; it can be used for any textual work, regardless of subject matter or whether it is published as a printed book. We recommend this License principally for works whose purpose is instruction or reference.

** 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains a notice placed by the copyright holder saying it can be distributed under the terms of this License. Such a notice grants a world-wide, royalty-free license, unlimited in duration, to use that work under the conditions stated herein. The Document, below, refers to any such manual or work. Any member of the public is a licensee, and is addressed as you. You accept the license if you copy, modify or distribute the work in a way requiring permission under copyright law.

A Modified Version of the Document means any work containing the Document or a portion of it, either copied verbatim, or with modifications and/or translated into another language.

A Secondary Section is a named appendix or a front-matter section of the Document that deals exclusively with the relationship of the publishers or authors of the Document to the Document's overall subject (or to related matters) and contains nothing that could fall directly within that overall subject. (Thus, if the Document is in part a textbook of mathematics, a Secondary Section may not explain any mathematics.) The relationship could be a matter of historical connection with the subject or with related matters, or of legal, commercial, philosophical, ethical or political position regarding them.

The Invariant Sections are certain Secondary Sections whose titles are designated, as being those of Invariant Sections, in the notice that says that the Document is released under this License. If a section does not fit the above definition of Secondary then it is not allowed to be designated as Invariant. The Document may contain zero Invariant Sections. If the Document does not identify any Invariant Sections then there are none.

The Cover Texts are certain short passages of text that are listed, as Front-Cover Texts or Back-Cover Texts, in the notice that says that the Document is released under this License. A Front-Cover Text may be at most 5 words, and a Back-Cover Text may be at most 25 words.

A Transparent copy of the Document means a machine-readable copy, represented in a format whose specification is available to the general public, that is suitable for revising the document straightforwardly with generic text editors or (for images composed of pixels) generic paint programs or (for drawings) some widely available drawing editor, and that is suitable for input to text formatters or for automatic translation to a variety of formats suitable for input to text formatters. A copy made in an otherwise Transparent file format whose markup, or absence of markup, has been arranged to thwart or discourage subsequent modification by readers is not Transparent. An image format is not Transparent if used for any substantial amount of text. A copy that is not Transparent is called Opaque.

Examples of suitable formats for Transparent copies include plain ASCII without markup, Texinfo input format, \LaTeX{} input format, SGML or XML using a publicly available DTD, and standard-conforming simple HTML, PostScript or PDF designed for human modification. Examples of transparent image formats include PNG, XCF and JPG. Opaque formats include proprietary formats that can be read and edited only by proprietary word processors, SGML or XML for which the DTD and/or processing tools are not generally available, and the machine-generated HTML, PostScript or PDF produced by some word processors for output purposes only.

The Title Page means, for a printed book, the title page itself, plus such following pages as are needed to hold, legibly, the material this License requires to appear in the title page. For works in formats which do not have any title page as such, Title Page means the text near the most prominent appearance of the work's title, preceding the beginning of the body of the text.

The publisher means any person or entity that distributes copies of the Document to the public.  A section Entitled XYZ means a named subunit of the Document whose title either is precisely XYZ or contains XYZ in parentheses following text that translates XYZ in another language. (Here XYZ stands for a specific section name mentioned below, such as Acknowledgements, Dedications, Endorsements, or History.) To Preserve the Title of such a section when you modify the Document means that it remains a section Entitled XYZ according to this definition.

The Document may include Warranty Disclaimers next to the notice which states that this License applies to the Document. These Warranty Disclaimers are considered to be included by reference in this License, but only as regards disclaiming warranties: any other implication that these Warranty Disclaimers may have is void and has no effect on the meaning of this License.

** 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or noncommercially, provided that this License, the copyright notices, and the license notice saying this License applies to the Document are reproduced in all copies, and that you add no other conditions whatsoever to those of this License. You may not use technical measures to obstruct or control the reading or further copying of the copies you make or distribute. However, you may accept compensation in exchange for copies. If you distribute a large enough number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may publicly display copies.

** 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed covers) of the Document, numbering more than 100, and the Document's license notice requires Cover Texts, you must enclose the copies in covers that carry, clearly and legibly, all these Cover Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on the back cover. Both covers must also clearly and legibly identify you as the publisher of these copies. The front cover must present the full title with all words of the title equally prominent and visible. You may add other material on the covers in addition. Copying with changes limited to the covers, as long as they preserve the title of the Document and satisfy these conditions, can be treated as verbatim copying in other respects.

If the required texts for either cover are too voluminous to fit legibly, you should put the first ones listed (as many as fit reasonably) on the actual cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than 100, you must either include a machine-readable Transparent copy along with each Opaque copy, or state in or with each Opaque copy a computer-network location from which the general network-using public has access to download using public-standard network protocols a complete Transparent copy of the Document, free of added material. If you use the latter option, you must take reasonably prudent steps, when you begin distribution of Opaque copies in quantity, to ensure that this Transparent copy will remain thus accessible at the stated location until at least one year after the last time you distribute an Opaque copy (directly or through your agents or retailers) of that edition to the public.

It is requested, but not required, that you contact the authors of the Document well before redistributing any large number of copies, to give them a chance to provide you with an updated version of the Document.

** 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the conditions of sections 2 and 3 above, provided that you release the Modified Version under precisely this License, with the Modified Version filling the role of the Document, thus licensing distribution and modification of the Modified Version to whoever possesses a copy of it. In addition, you must do these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that of the Document, and from those of previous versions (which should, if there were any, be listed in the History section of the Document). You may use the same title as a previous version if the original publisher of that version gives permission. 

B. List on the Title Page, as authors, one or more persons or entities responsible for authorship of the modifications in the Modified Version, together with at least five of the principal authors of the Document (all of its principal authors, if it has fewer than five), unless they release you from this requirement. 

C. State on the Title page the name of the publisher of the Modified Version, as the publisher. 

D. Preserve all the copyright notices of the Document. 

E. Add an appropriate copyright notice for your modifications adjacent to the other copyright notices. 

F. Include, immediately after the copyright notices, a license notice giving the public permission to use the Modified Version under the terms of this License, in the form shown in the Addendum below.  

G. Preserve in that license notice the full lists of Invariant Sections and required Cover Texts given in the Document's license notice. 

H. Include an unaltered copy of this License. 

I. Preserve the section Entitled History, Preserve its Title, and add to it an item stating at least the title, year, new authors, and publisher of the Modified Version as given on the Title Page. If there is no section Entitled History in the Document, create one stating the title, year, authors, and publisher of the Document as given on its Title Page, then add an item describing the Modified Version as stated in the previous sentence. 

J. Preserve the network location, if any, given in the Document for public access to a Transparent copy of the Document, and likewise the network locations given in the Document for previous versions it was based on. These may be placed in the History section. You may omit a network location for a work that was published at least four years before the Document itself, or if the original publisher of the version it refers to gives permission. 

K. For any section Entitled Acknowledgements or Dedications, Preserve the Title of the section, and preserve in the section all the substance and tone of each of the contributor acknowledgements and/or dedications given therein. 
L. Preserve all the Invariant Sections of the Document, unaltered in their text and in their titles. Section numbers or the equivalent are not considered part of the section titles. 

M. Delete any section Entitled Endorsements. Such a section may not be included in the Modified Version. 

N. Do not retitle any existing section to be Entitled Endorsements or to conflict in title with any Invariant Section. 

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that qualify as Secondary Sections and contain no material copied from the Document, you may at your option designate some or all of these sections as invariant. To do this, add their titles to the list of Invariant Sections in the Modified Version's license notice. These titles must be distinct from any other section titles.

You may add a section Entitled Endorsements, provided it contains nothing but endorsements of your Modified Version by various parties--for example, statements of peer review or that the text has been approved by an organization as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts in the Modified Version. Only one passage of Front-Cover Text and one of Back-Cover Text may be added by (or through arrangements made by) any one entity. If the Document already includes a cover text for the same cover, previously added by you or by arrangement made by the same entity you are acting on behalf of, you may not add another; but you may replace the old one, on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give permission to use their names for publicity for or to assert or imply endorsement of any Modified Version.

** 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License, under the terms defined in section 4 above for modified versions, provided that you include in the combination all of the Invariant Sections of all of the original documents, unmodified, and list them all as Invariant Sections of your combined work in its license notice, and that you preserve all their Warranty Disclaimers.

The combined work need only contain one copy of this License, and multiple identical Invariant Sections may be replaced with a single copy. If there are multiple Invariant Sections with the same name but different contents, make the title of each such section unique by adding at the end of it, in parentheses, the name of the original author or publisher of that section if known, or else a unique number. Make the same adjustment to the section titles in the list of Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled History in the various original documents, forming one section Entitled History;
likewise combine any sections Entitled Acknowledgements, and any sections Entitled Dedications. You must delete all sections Entitled Endorsements.

** 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents released under this License, and replace the individual copies of this License in the various documents with a single copy that is included in the collection, provided that you follow the rules of this License for verbatim copying of each of the documents in all other respects. 

You may extract a single document from such a collection, and distribute it individually under this License, provided you insert a copy of this License into the extracted document, and follow this License in all other respects regarding verbatim copying of that document.

** 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and independent documents or works, in or on a volume of a storage or distribution medium, is called an aggregate if the copyright resulting from the compilation is not used to limit the legal rights of the compilation's users beyond what the individual works permit. When the Document is included in an aggregate, this License does not apply to the other works in the aggregate which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the Document, then if the Document is less than one half of the entire aggregate, the Document's Cover Texts may be placed on covers that bracket the Document within the aggregate, or the electronic equivalent of covers if the Document is in electronic form. Otherwise they must appear on printed covers that bracket the whole aggregate.

** 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute translations of the Document under the terms of section 4. Replacing Invariant Sections with translations requires special permission from their copyright holders, but you may include translations of some or all Invariant Sections in addition to the original versions of these Invariant Sections. You may include a translation of this License, and all the license notices in the Document, and any Warranty Disclaimers, provided that you also include the original English version of this License and the original versions of those notices and disclaimers. In case of a disagreement between the translation and the original version of this License or a notice or disclaimer, the original version will prevail.

If a section in the Document is Entitled Acknowledgements, Dedications, or History, the requirement (section 4) to Preserve its Title (section 1) will typically require changing the actual title.

** 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as expressly provided under this License. Any attempt otherwise to copy, modify, sublicense, or distribute it is void, and will automatically terminate your rights under this License.

However, if you cease all violation of this License, then your license from a particular copyright holder is reinstated (a) provisionally, unless and until the copyright holder explicitly and finally terminates your license, and (b) permanently, if the copyright holder fails to notify you of the violation by some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated permanently if the copyright holder notifies you of the violation by some reasonable means, this is the first time you have received notice of violation of this License (for any work) from that copyright holder, and you cure the violation prior to 30 days after your receipt of the notice. 

Termination of your rights under this section does not terminate the licenses of parties who have received copies or rights from you under this License. If your rights have been terminated and not permanently reinstated, receipt of a copy of some or all of the same material does not give you any rights to use it.

** 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free Documentation License from time to time. Such new versions will be similar in spirit to the present version, but may differ in detail to address new problems or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the Document specifies that a particular numbered version of this License or any later version applies to it, you have the option of following the terms and conditions either of that specified version or of any later version that has been published (not as a draft) by the Free Software Foundation. If the Document does not specify a version number of this License, you may choose any version ever published (not as a draft) by the Free Software Foundation. If the Document specifies that a proxy can decide which future versions of this License can be used, that proxy's public statement of acceptance of a version permanently authorizes you to choose that version for the Document.

** 11. RELICENSING

Massive Multiauthor Collaboration Site (or MMC Site) means any World Wide Web server that publishes copyrightable works and also provides prominent facilities for anybody to edit those works. A public wiki that anybody can edit is an example of such a server. A Massive Multiauthor Collaboration (or MMC) contained in the site means any set of copyrightable works thus published on the MMC site.

CC-BY-SA means the Creative Commons Attribution-Share Alike 3.0 license published by Creative Commons Corporation, a not-for-profit corporation with a principal place of business in San Francisco, California, as well as future copyleft versions of that license published by that same organization.

Incorporate means to publish or republish a Document, in whole or in part, as part of another Document.

An MMC is eligible for relicensing if it is licensed under this License, and if all works that were first published under this License somewhere other than this MMC, and subsequently incorporated in whole or in part into the MMC, (1) had no cover texts or invariant sections, and (2) were thus incorporated prior to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC is eligible for relicensing.

** ADDENDUM: How to use this License for your documents

To use this License in a document you have written, include a copy of the License in the document and put the following copyright and license notices just after the title page: 

#+begin_quote
\noindent Copyright (c) YEAR YOUR NAME. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.3 or any later version published by the Free Software Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included in the section entitled GNU Free Documentation License.
#+end_quote

If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts, replace the with...Texts. line with this:

#+begin_quote
\noindent with the Invariant Sections being LIST THEIR TITLES, with the Front-Cover Texts being LIST, and with the Back-Cover Texts being LIST.
#+end_quote

If you have Invariant Sections without Cover Texts, or some other combination of the three, merge those two alternatives to suit the situation.

If your document contains nontrivial examples of program code, we recommend releasing these examples in parallel under your choice of free software license, such as the GNU General Public License, to permit their use in free software. 

* History
\label{cha:History}

| Title:     | Introduction to Probability and Statistics Using \textsf{R} |
| Year:      | 2011                                                        |
| Authors:   | G. Jay Kerns                                                |
| Publisher: | G. Jay Kerns                                                |

#+latex: \vfill{}

* Data
\label{cha:data}

This appendix is a reference of sorts regarding some of the data structures a statistician is likely to encounter. We discuss their salient features and idiosyncrasies.

** Data Structures \label{sec:Data-Structures}


*** Vectors

See the ``Vectors and Assignment'' section of /An Introduction to/ \textsf{R}. A vector is an ordered sequence of elements, such as numbers, characters, or logical values, and there may be =NA='s present. We usually make vectors with the assignment operator =<-=.

#+begin_src R :exports both :results output pp 
x <- c(3, 5, 9)
#+end_src

Vectors are atomic in the sense that if you try to mix and match elements of different modes then all elements will be coerced to the most convenient common mode.

#+begin_src R :exports both :results output pp 
y <- c(3, "5", TRUE)
#+end_src

In the example all elements were coerced to /character/ mode. We can test whether a given object is a vector with =is.vector= and can coerce an object (if possible) to a vector with =as.vector=.

*** Matrices and Arrays

See the ``Arrays and Matrices'' section of /An Introduction to/ \textsf{R}. Loosely speaking, a matrix is a vector that has been reshaped into rectangular form, and an array is a multidimensional matrix. Strictly speaking, it is the other way around: an array is a data vector with a dimension attribute (=dim=), and a matrix is the special case of an array with only two dimensions. We can construct a matrix with the =matrix= function. 

#+begin_src R :exports both :results output pp 
matrix(letters[1:6], nrow = 2, ncol = 3)
#+end_src

Notice the order of the matrix entries, which shows how the matrix is populated by default. We can change this with the =byrow= argument:

#+begin_src R :exports both :results output pp 
matrix(letters[1:6], nrow = 2, ncol = 3, byrow = TRUE)
#+end_src

We can test whether a given object is a matrix with =is.matrix= and can coerce an object (if possible) to a matrix with =as.matrix=. As a final example watch what happens when we mix and match types in the first argument:

#+begin_src R :exports both :results output pp 
matrix(c(1,"2",NA, FALSE), nrow = 2, ncol = 3)
#+end_src

Notice how all of the entries were coerced to character for the final result (except =NA=). Also notice how the four values were /recycled/ to fill up the six entries of the matrix.

The standard arithmetic operations work element-wise with matrices.

#+begin_src R :exports both :results output pp 
A <- matrix(1:6, 2, 3)
B <- matrix(2:7, 2, 3)
A + B
A * B
#+end_src

If you want the standard definition of matrix multiplication then use the =%*%= function. If we were to try =A %*% B= we would get an error because the dimensions do not match correctly, but for fun, we could transpose =B= to get conformable matrices. The transpose function =t= only works for matrices (and data frames).

#+begin_src R :exports both :results output pp 
try(A * B)     # an error
A %*% t(B)     # this is alright
#+end_src

To get the ordinary matrix inverse use the =solve= function: 

#+begin_src R :exports both :results output pp 
solve(A %*% t(B))     # input matrix must be square
#+end_src

Arrays more general than matrices, and some functions (like transpose) do not work for the more general array. Here is what an array looks like: 

#+begin_src R :exports both :results output pp 
array(LETTERS[1:24], dim = c(3,4,2))
#+end_src

We can test with =is.array= and may coerce with =as.array=.

*** Data Frames

A data frame is a rectangular array of information with a special status in \textsf{R}. It is used as the fundamental data structure by many of the modeling functions. It is like a matrix in that all of the columns must be the same length, but it is more general than a matrix in that columns are allowed to have different modes.

#+begin_src R :exports both :results output pp 
x <- c(1.3, 5.2, 6)
y <- letters[1:3]
z <- c(TRUE, FALSE, TRUE)
A <- data.frame(x, y, z)
A
#+end_src

Notice the =names= on the columns of =A=. We can change those with the =names= function.

#+begin_src R :exports both :results output pp 
names(A) <- c("Fred","Mary","Sue")
A
#+end_src

Basic command is =data.frame=. You can test with =is.data.frame= and you can coerce with =as.data.frame=.


*** Lists
A list is more general than a data frame.

*** Tables
The word ``table'' has a special meaning in \textsf{R}. More precisely, a contingency table is an object of class =table= which is an array.

Suppose you have a contingency table and would like to do descriptive or inferential statistics on it. The default form of the table is usually inconvenient to use unless we are working with a function specially tailored for tables. Here is how to transform your data to a more manageable form, namely, the raw data used to make the table.

First, we coerce the table to a data frame with: 

#+begin_src R :exports both :results output pp 
A <- as.data.frame(Titanic)
head(A)
#+end_src

Note that there are as many preliminary columns of =A= as there are dimensions to the table. The rows of =A= contain every possible combination of levels from each of the dimensions. There is also a =Freq= column, which shows how many observations there were at that particular combination of levels. 

The form of =A= is often sufficient for our purposes, but more often we need to do more work: we would usually like to repeat each row of =A= exactly the number of times shown in the =Freq= column. The =reshape= package \cite{Wickhamreshape} has the function =untable= designed for that very purpose: 

#+begin_src R :exports both :results output pp 
library(reshape)
B <- with(A, untable(A, Freq))
head(B)
#+end_src

Now, this is more like it. Note that we slipped in a call to the =with= function, which was done to make the call to =untable= more pretty; we could just as easily have done
:  untable(TitanicDF, A$Freq)


The only fly in the ointment is the lingering =Freq= column which has repeated values that do not have any meaning any more. We could just ignore it, but it would be better to get rid of the meaningless column so that it does not cause trouble later. While we are at it, we could clean up the =rownames=, too.

#+begin_src R :exports both :results output pp 
C <- B[, -5]
rownames(C) <- 1:dim(C)[1]
head(C)
#+end_src


*** More about Tables
Suppose you want to make a table that looks like this:

There are at least two ways to do it.

- Using a matrix:
  #+begin_src R :exports both :results output pp 
  tab <- matrix(1:6, nrow = 2, ncol = 3)
  rownames(tab) <- c('first', 'second')
  colnames(tab) <- c('A', 'B', 'C')
  tab  # Counts
  #+end_src
   - note that the columns are filled in consecutively by default. If you want to fill the data in by rows then do =byrow = TRUE= in the =matrix= command.

- Using a dataframe
  #+begin_src R :exports both :results output pp 
  p <- c("milk","tea")
  g <- c("milk","tea")
  catgs <- expand.grid(poured = p, guessed = g)
  cnts <- c(3, 1, 1, 3)
  D <- cbind(catgs, count = cnts)
  xtabs(count ~ poured + guessed, data = D)
  #+end_src
   - again, the data are filled in column-wise.
   - the object is a dataframe
   - if you want to store it as a table then do =A <- xtabs(count ~ poured + guessed, data = D)=


** Importing Data \label{sec:Importing-A-Data}

Statistics is the study of data, so the statistician's first step is usually to obtain data from somewhere or another and read them into \textsf{R}. In this section we describe some of the most common sources of data and how to get data from those sources into a running \textsf{R} session.

For more information please refer to the \textsf{R} /Data Import/Export Manual/, \cite{rstatenv} and /An Introduction to/ \textsf{R}, \cite{Venables2010}.

*** Data in Packages

There are many data sets stored in the =datasets= package of base \textsf{R}. To see a list of them all issue the command =data(package = "datasets")=. The output is omitted here because the list is so long. The names of the data sets are listed in the left column. Any data set in that list is already on the search path by default, which means that a user can use it immediately without any additional work. 

There are many other data sets available in the thousands of contributed packages. To see the data sets available in those packages that are currently loaded into memory issue the single command =data()=. If you would like to see all of the data sets that are available in all packages that are installed on your computer (but not necessarily loaded), issue the command 

:  data(package = .packages(all.available = TRUE))

To load the data set =foo= in the contributed package =bar= issue the commands =library(bar)= followed by =data(foo)=, or just the single command  

:  data(foo, package = "bar")

*** Text Files
Many sources of data are simple text files. The entries in the file are separated by delimeters such as TABS (tab-delimeted), commas (comma separated values, or =.csv=, for short) or even just white space (no special name). A lot of data on the Internet are stored with text files, and even if they are not, a person can copy-paste information from a web page to a text file, save it on the computer, and read it into \textsf{R}. 

*** Other Software Files
Often the data set of interest is stored in some other, proprietary, format by third-party software such as Minitab, SAS, or SPSS. The =foreign= package supports import/conversion from many of these formats. Please note, however, that data sets from other software sometimes have properties with no direct analogue in \textsf{R}. In those cases the conversion process may lose some information which will need to be reentered manually from within \textsf{R}. See the /Data Import/Export Manual/.

As an example, suppose the data are stored in the SPSS file =foo.sav= which the user has copied to the working directory; it can be imported with the commands

#+begin_src R :exports code :eval never
library(foreign)
read.spss("foo.sav")
#+end_src

See =?read.spss= for the available options to customize the file import. Note that the \textsf{R} Commander will import many of the common file types with a menu driven interface.

*** Importing a Data Frame

The basic command is =read.table=.

** Creating New Data Sets \label{sec:Creating-New-Data}
Using =c=
Using =scan=
Using the \textsf{R} Commander.

** Editing Data \label{sec:Editing-Data-Sets}
*** Editing Data Values
*** Inserting Rows and Columns
*** Deleting Rows and Columns
*** Sorting Data

We can sort a vector with the =sort= function. Normally we have a data frame of several columns (variables) and many, many rows (observations). The goal is to shuffle the rows so that they are ordered by the values of one or more columns. This is done with the =order= function. 

For example, we may sort all of the rows of the =Puromycin= data (in ascending order) by the variable =conc= with the following: 

#+begin_src R :exports both :results output pp 
Tmp <- Puromycin[order(Puromycin$conc), ]
head(Tmp)
#+end_src

We can accomplish the same thing with the command 

#+begin_src R :exports code :eval never
with(Puromycin, Puromycin[order(conc), ])
#+end_src

We can sort by more than one variable. To sort first by =state= and next by =conc= do 

#+begin_src R :exports code :eval never
with(Puromycin, Puromycin[order(state, conc), ])
#+end_src

If we would like to sort a numeric variable in descending order then we put a minus sign in front of it. 

#+begin_src R :exports both :results output pp 
Tmp <- with(Puromycin, Puromycin[order(-conc), ])
head(Tmp)
#+end_src

If we would like to sort by a character (or factor) in decreasing order then we can use the =xtfrm= function which produces a numeric vector in the same order as the character vector.

#+begin_src R :exports both :results output pp 
Tmp <- with(Puromycin, Puromycin[order(-xtfrm(state)), ])
head(Tmp)
#+end_src

** Exporting Data \label{sec:Exporting-a-Data}

The basic function is =write.table=. The =MASS= package also has a =write.matrix= function.

** Reshaping Data \label{sec:Reshaping-a-Data}
- Aggregation
- Convert Tables to data frames and back

=rbind=, =cbind=
=ab[order(ab[,1]),]=
=complete.cases=
=aggregate=
=stack=

* Mathematical Machinery
\label{cha:Mathematical-Machinery}

This appendix houses many of the standard definitions and theorems that are used at some point during the narrative. It is targeted for someone reading the book who forgets the precise definition of something and would like a quick reminder of an exact statement. No proofs are given, and the interested reader should consult a good text on Calculus (say, Stewart \cite{Stewart2008} or Apostol \cite{Apostol1967,ApostolI1967}), Linear Algebra (say, Strang \cite{Strang1988} and Magnus \cite{Magnus1999}), Real Analysis (say, Folland \cite{Folland1999}, or Carothers \cite{Carothers2000}), or Measure Theory (Billingsley \cite{Billingsley1995}, Ash \cite{Ash2000}, Resnick \cite{Resnick1999}) for details. 


** Set Algebra \label{sec:The-Algebra-of}

We denote sets by capital letters, \(A\), \(B\), \(C\), /etc/. The letter \(S\) is reserved for the sample space, also known as the universe or universal set, the set which contains all possible elements. The symbol \(\emptyset\) represents the empty set, the set with no elements. 


*** Set Union, Intersection, and Difference

Given subsets \(A\) and \(B\), we may manipulate them in an algebraic fashion. To this end, we have three set operations at our disposal: union, intersection, and difference. Below is a table summarizing the pertinent information about these operations.

#+CAPTION: [Set operations]{Set operations.}
#+LABEL: tab:Set-Operations
| Name         | Denoted             | Defined by elements   | \textsf{R} syntax |
|--------------+---------------------+-----------------------+-------------------|
| Union        | \(A\cup B\)           | in \(A\) or \(B\) or both | =union(A, B)=     |
| Intersection | \(A\cap B\)           | in both \(A\) and \(B\)   | =intersect(A, B)= |
| Difference   | \(A\textbackslash B\) | in \(A\) but not in \(B\) | =setdiff(A, B)=   |
| Complement   | \(A^{c}\)             | in \(S\) but not in \(A\) | =setdiff(S, A)=   |



*** Identities and Properties

1. \(A\cup\emptyset=A,\quad A\cap\emptyset=\emptyset\)
1. \(A\cup S=S,\quad A\cap S=A\)
1. \(A\cup A^{c}=S\), \(A\cap A^{c}=\emptyset\)
1. \((A{}^{c})^{c}=A\)
1. The Commutative Property: 
   \begin{equation}
   A \cup B = B\cup A,\quad A\cap B = B\cap A
   \end{equation}
1. The Associative Property: 
   \begin{equation}
   (A\cup B)\cup C=A\cup(B\cup C),\quad(A\cap B)\cap C=A\cap(B\cap C)
   \end{equation}
1. The Distributive Property: 
   \begin{equation}
   A\cup(B\cap C)=(A\cup B)\cap(A\cup B),\quad A\cap(B\cup C)=(A\cap B)\cup(A\cap B)
   \end{equation}
1. DeMorgan's Laws
   \begin{equation}
   (A\cup B)^{c}=A^{c}\cap B^{c}\quad\mbox{and}\quad(A\cap B)^{c}=A^{c}\cup B^{c},
   \end{equation}
   or more generally,
   \begin{equation}
   \left(\bigcup_{\alpha}A_{\alpha}\right)^{c}=\bigcap_{\alpha}A_{\alpha}^{c},\quad\mbox{and}\quad\left(\bigcap_{\alpha}A_{\alpha}\right)^{c}=\bigcup_{\alpha}A_{\alpha}^{c}
   \end{equation}

** Differential and Integral Calculus \label{sec:Differential-and-Integral}

A function \(f\) of one variable is said to be one-to-one if no two distinct \(x\) values are mapped to the same \(y=f(x)\) value. To show that a function is one-to-one we can either use the horizontal line test or we may start with the equation \(f(x_{1}) = f(x_{2})\) and use algebra to show that it implies \(x_{1} = x_{2}\).

*** Limits and Continuity
#+latex: \begin{defn}
Let \(f\) be a function defined on some open interval that contains the number \(a\), except possibly at \(a\) itself. Then we say the /limit of/ \(f(x)\) /as/ \(x\) /approaches/ \(a\) /is/ \(L\), and we write 
\begin{equation}
\lim_{x \to a}f(x) = L,
\end{equation}
if for every \(\epsilon > 0\) there exists a number \(\delta > 0\) such that \(0 < |x-a| < \delta\) implies \(|f(x) - L| < \epsilon\).
#+latex: \end{defn}

#+latex: \begin{defn}
A function \(f\) is /continuous at a number/ \(a\) if 
\begin{equation}
\lim_{x \to a} f(x) = f(a).
\end{equation}
The function \(f\) is /right-continuous at the number/ \(a\) if \(\lim_{x\to a^{+}}f(x)=f(a)\), and /left-continuous/ at \(a\) if \(\lim_{x\to a^{-}}f(x)=f(a)\). Finally, the function \(f\) is /continuous on an interval/ \(I\) if it is continuous at every number in the interval. 
#+latex: \end{defn}

*** Differentiation
#+latex: \begin{defn}
The /derivative of a function/ \(f\) /at a number/ \(a\), denoted by \(f'(a)\), is
\begin{equation}
f'(a)=\lim_{h\to0}\frac{f(a+h)-f(a)}{h},
\end{equation}
provided this limit exists.
A function is /differentiable at/ \(a\) if \(f'(a)\) exists. It is /differentiable on an open interval/ \((a,b)\) if it is differentiable at every number in the interval.
#+latex: \end{defn}



#+latex: \paragraph*{Differentiation Rules}
In the table that follows, \(f\) and \(g\) are differentiable functions and \(c\) is a constant.

#+CAPTION: [Differentiation rules]{Differentiation rules.}
#+LABEL: tab:Differentiation-Rules
| \(\frac{\mathrm{d}}{\mathrm{d} x}c=0\) | \(\frac{\mathrm{d}}{\mathrm{d} x}x^{n}=nx^{n-1}\) | \((cf)'=cf'\)                                       |
| \((f\pm g)'=f'\pm g'\)       | \((fg)'=f'g+fg'\)                       | \(\left(\frac{f}{g}\right)'=\frac{f'g-fg'}{g^{2}}\) |

#+latex: \begin{thm}
Chain Rule: If \(f\) and \(g\) are both differentiable and \(F=f\circ g\) is the composite function defined by \(F(x)=f[g(x)]\), then \(F\) is differentiable and \(F'(x) = f'[ g(x) ] \cdot g'(x)\).  
#+latex: \end{thm}

#+latex: \paragraph*{Useful Derivatives}


#+CAPTION: [Some derivatives]{Some derivatives.}
#+LABEL: tab:Useful-Derivatives
| \(\frac{\mathrm{d}}{\mathrm{d} x}\mathrm{e}^{x}=\mathrm{e}^{x}\) | \(\frac{\mathrm{d}}{\mathrm{d} x}\ln x=x^{-1}\)     | \(\frac{\mathrm{d}}{\mathrm{d} x}\sin x=\cos x\)             |
| \(\frac{\mathrm{d}}{\mathrm{d} x}\cos x=-\sin x\)  | \(\frac{\mathrm{d}}{\mathrm{d} x}\tan x=\sec^{2}x\) | \(\frac{\mathrm{d}}{\mathrm{d} x}\tan^{-1}x=(1+x^{2})^{-1}\) |
|                                        |                                         |                                                  |

*** Optimization
#+latex: \begin{defn}
A /critical number/ of the function \(f\) is a value \(x^{\ast}\) for which \(f'(x^{\ast})=0\) or for which \(f'(x^{\ast})\) does not exist.
#+latex: \end{defn}

#+latex: \begin{thm}
\label{thm:First-Derivative-Test}
First Derivative Test. If \(f\) is differentiable and if \(x^{\ast}\) is a critical number of \(f\) and if \(f'(x)\geq0\) for \(x\leq x^{\ast}\) and \(f'(x)\leq0\) for \(x\geq x^{\ast}\), then \(x^{\ast}\) is a local maximum of \(f\). If \(f'(x)\leq0\) for \(x\leq x^{\ast}\) and \(f'(x)\geq0\) for \(x\geq x^{\ast}\) , then \(x^{\ast}\) is a local minimum of \(f\).
#+latex: \end{thm}

#+latex: \begin{thm}
Second Derivative Test. If \(f\) is twice differentiable and if \(x^{\ast}\) is a critical number of \(f\), then \(x^{\ast}\) is a local maximum of \(f\) if \(f''(x^{\ast})<0\) and \(x^{\ast}\) is a local minimum of \(f\) if \(f''(x^{\ast})>0\).
#+latex: \end{thm}

*** Integration
As it turns out, there are all sorts of things called ``integrals'', each defined in its own idiosyncratic way. There are /Riemann/ integrals, /Lebesgue/ integrals, variants of these called /Stieltjes/ integrals, /Daniell/ integrals, /Ito/ integrals, and the list continues. Given that this is an introductory book, we will use the Riemannian integral with the caveat that the Riemann integral is /not/ the integral that will be used in more advanced study.

#+latex: \begin{defn}
Let \(f\) be defined on \([a,b]\), a closed interval of the real line. For each \(n\), divide \([a,b]\) into subintervals \([x_{i},x_{i+1}]\), \(i=0,1,\ldots,n-1\), of length \(\Delta x_{i}=(b-a)/n\) where \(x_{0}=a\) and \(x_{n}=b\), and let \(x_{i}^{\ast}\) be any points chosen from the respective subintervals. Then the /definite integral/ of \(f\) from \(a\) to \(b\) is defined by
\begin{equation}
\int_{a}^{b}f(x)\,\mathrm{d} x=\lim_{n\to\infty}\sum_{i=0}^{n-1}f(x_{i}^{\ast})\,\Delta x_{i},
\end{equation}
provided the limit exists, and in that case, we say that \(f\) is /integrable/ from \(a\) to \(b\). 
#+latex: \end{defn}

#+latex: \begin{thm}
The Fundamental Theorem of Calculus. Suppose \(f\) is continuous on \([a,b]\). Then
1. the function \(g\) defined by \(g(x)=\int_{a}^{x}f(t)\:\mathrm{d} t\), \(a\leq x\leq b\), is continuous on \([a,b]\) and differentiable on \((a,b)\) with \(g'(x)=f(x)\).
1. \(\int_{a}^{b}f(x)\,\mathrm{d} x=F(b)-F(a)\), where \(F\) is any /antiderivative/ of \(f\), that is, any function \(F\) satisfying \(F'=f\).
#+latex: \end{thm}


#+latex: \paragraph*{Change of Variables}
#+latex: \begin{thm}
If \(g\) is a differentiable function whose range is the interval \([a,b]\) and if both \(f\) and \(g'\) are continuous on the range of \(u = g(x)\), then
\begin{equation}
\int_{g(a)}^{g(b)}f(u)\:\mathrm{d} u=\int_{a}^{b}f[g(x)]\: g'(x)\:\mathrm{d} x.
\end{equation}
#+latex: \end{thm}

#+latex: \paragraph*{Useful Integrals}


#+CAPTION: [Some integrals (constants of integration omitted)]{Some integrals (constants of integration omitted).}
#+LABEL: tab:Useful-Integrals
| \(\int x^{n}\,\mathrm{d} x=x^{n+1}/(n+1),\ n\neq-1\) | \(\int\mathrm{e}^{x}\,\mathrm{d} x=\mathrm{e}^{x}\) | \(\int x^{-1}\,\mathrm{d} x=\ln \abs(x) \)      |
| \(\int\tan x\:\mathrm{d} x=\ln \abs(\sec x)\)        | \(\int a^{x}\,\mathrm{d} x=a^{x}/\ln a\)            | \(\int(x^{2}+1)^{-1}\,\mathrm{d} x=\tan^{-1}x\) |

#+latex: \paragraph*{Integration by Parts}

\begin{equation}
\int u\:\mathrm{d} v=uv-\int v\:\mathrm{d} u
\end{equation}
#+latex: \begin{thm}
L'H\^ opital's Rule. Suppose \(f\) and \(g\) are differentiable and \(g'(x)\neq0\) near \(a\), except possibly at \(a\). Suppose that the limit 
\begin{equation}
\lim_{x\to a}\frac{f(x)}{g(x)}
\end{equation}
is an indeterminate form of type \(\frac{0}{0}\) or \(\infty/\infty\). Then
\begin{equation}
\lim_{x\to a}\frac{f(x)}{g(x)}=\lim_{x\to a}\frac{f'(x)}{g'(x)},
\end{equation}
provided the limit on the right-hand side exists or is infinite.
#+latex: \end{thm}

#+latex: \paragraph*{Improper Integrals}

If \(\int_{a}^{t}f(x)\mathrm{d} x\) exists for every number \(t\geq a\), then we define 
\begin{equation}
\int_{a}^{\infty}f(x)\,\mathrm{d} x=\lim_{t\to\infty}\int_{a}^{t}f(x)\,\mathrm{d} x,
\end{equation}
provided this limit exists as a finite number, and in that case we say that \(\int_{a}^{\infty}f(x)\,\mathrm{d} x\) is /convergent/. Otherwise, we say that the improper integral is /divergent/.

If \(\int_{t}^{b}f(x)\,\mathrm{d} x\) exists for every number \(t\leq b\), then we define
\begin{equation}
\int_{-\infty}^{b}f(x)\,\mathrm{d} x=\lim_{t\to-\infty}\int_{t}^{b}f(x)\,\mathrm{d} x,
\end{equation}
provided this limit exists as a finite number, and in that case we say that \(\int_{-\infty}^{b}f(x)\,\mathrm{d} x\) is /convergent/. Otherwise, we say that the improper integral is /divergent/.

If both \(\int_{a}^{\infty}f(x)\,\mathrm{d} x\) and \(\int_{-\infty}^{a}f(x)\,\mathrm{d} x\) are convergent, then we define
\begin{equation}
\int_{-\infty}^{\infty}f(x)\,\mathrm{d} x=\int_{-\infty}^{a}f(x)\,\mathrm{d} x+\int_{a}^{\infty}f(x)\mathrm{d} x,
\end{equation}
and we say that \(\int_{-\infty}^{\infty}f(x)\,\mathrm{d} x\) is /convergent/. Otherwise, we say that the improper integral is /divergent/.


** Sequences and Series \label{sec:Sequences-and-Series}

A /sequence/ is an ordered list of numbers, \(a_{1}\), \(a_{2}\), \(a_{3}\), ..., \(a_{n} =\left(a_{k}\right)_{k=1}^{n}\). A sequence may be finite or infinite. In the latter case we write \(a_{1}\), \(a_{2}\), \(a_{3}\), ... \( =\left(a_{k}\right)_{k=1}^{\infty}\). We say that /the infinite sequence/ \(\left(a_{k}\right)_{k=1}^{\infty}\) /converges to the finite limit/ L, and we write
\begin{equation}
\lim_{k\to\infty}a_{k} = L,
\end{equation}
if for every \(\epsilon > 0\) there exists an integer \(N \geq 1\) such that \(|a_{k} - L| < \epsilon\) for all \(k \geq N\). We say that /the infinite sequence/ \(\left(a_{k}\right)_{k=1}^{\infty}\) /diverges to/ \(+\infty\) (or \( -\infty\)) if for every \(M\geq0\) there exists an integer \(N\geq1\) such that \(a_{k} \geq M\) for all \(k \geq N\) (or \(a_{k} \leq - M\) for all \(k \geq N\)).


*** Finite Series

\begin{equation}
\sum_{k=1}^{n}k=1+2+\cdots+n=\frac{n(n+1)}{2}\label{eq:gauss-series}
\end{equation}
\begin{equation}
\sum_{k=1}^{n}k^{2}=1^{2}+2^{2}+\cdots+n^{2}=\frac{n(n+1)(2n+3)}{6}\label{eq:gauss-series-sq}
\end{equation}


#+latex: \paragraph*{The Binomial Series}
\begin{equation}
\sum_{k=0}^{n}{n \choose k}\, a^{n-k}b^{k}=(a+b)^{n}\label{eq:binom-series}
\end{equation}

*** Infinite Series

Given an infinite sequence of numbers \(a_{1}\), \(a_{2}\), \(a_{3}\), ...\(=\left(a_{k}\right)_{k=1}^{\infty}\), let \(s_{n}\) denote the /partial sum/ of the first \(n\) terms:
\begin{equation}
s_{n}=\sum_{k=1}^{n}a_{k}=a_{1}+a_{2}+\cdots+a_{n}.
\end{equation}
If the sequence \(\left(s_{n}\right)_{n=1}^{\infty}\) converges to a finite number \(S\) then we say that the infinite series \(\sum_{k}a_{k}\) is /convergent/ and write
\begin{equation}
\sum_{k=1}^{\infty}a_{k}=S.
\end{equation}
Otherwise we say the infinite series is /divergent/.


*** Rules for Series

Let \(\left(a_{k}\right)_{k=1}^{\infty}\) and \(\left(b_{k}\right)_{k=1}^{\infty}\) be infinite sequences and let \(c\) be a constant.

\begin{equation}
\sum_{k=1}^{\infty}ca_{k}=c\sum_{k=1}^{\infty}a_{k}
\end{equation}
\begin{equation}
\sum_{k=1}^{\infty}(a_{k}\pm b_{k})=\sum_{k=1}^{\infty}a_{k}\pm\sum_{k=1}^{\infty}b_{k}
\end{equation}

In both of the above the series on the left is convergent if the series on the right is (are) convergent.

#+latex: \paragraph*{The Geometric Series}
\begin{equation}
\sum_{k=0}^{\infty} x^{k} = \frac{1}{1 - x},\quad|x| < 1.\label{eq:geom-series}
\end{equation}

#+latex: \paragraph*{The Exponential Series}
\begin{equation}
\sum_{k=0}^{\infty}\frac{x^{k}}{k!} = \mathrm{e}^{x},\quad -\infty < x < \infty. \label{eq:exp-series}
\end{equation}

Other Series
\begin{equation}
\sum_{k=0}^{\infty}{m+k-1 \choose m-1}x^{k}=\frac{1}{(1-x)^{m}},\quad|x|<1.\label{eq:negbin-series}
\end{equation}
\begin{equation}
-\sum_{k=1}^{\infty}\frac{x^{n}}{n}=\ln(1-x),\quad|x|<1.\label{eq:log-series}
\end{equation}
\begin{equation}
\sum_{k=0}^{\infty}{n \choose k}x^{k}=(1+x)^{n},\quad|x|<1.\label{eq:binom-series-infinite}
\end{equation}



*** Taylor Series

If the function \(f\) has a /power series/ representation at the point \(a\) with radius of convergence \(R>0\), that is, if
\begin{equation}
f(x)=\sum_{k=0}^{\infty}c_{k}(x-a)^{k},\quad|x-a|<R,
\end{equation}
for some constants \(\left(c_{k}\right)_{k=0}^{\infty}\), then \(c_{k}\) must be
\begin{equation}
c_{k}=\frac{f^{(k)}(a)}{k!},\quad k=0,1,2,\ldots
\end{equation}
Furthermore, the function \(f\) is differentiable on the open interval \((a-R,\, a+R)\) with
\begin{equation}
f'(x)=\sum_{k=1}^{\infty}kc_{k}(x-a)^{k-1},\quad|x-a|<R,
\end{equation}
\begin{equation}
\int f(x)\,\mathrm{d} x=C+\sum_{k=0}^{\infty}c_{k}\frac{(x-a)^{k+1}}{k+1},\quad|x-a|<R,
\end{equation}
in which case both of the above series have radius of convergence \(R\).


** The Gamma Function \label{sec:The-Gamma-Function}

The /Gamma function/ \(\Gamma\) will be defined in this book according to the formula
\begin{equation}
\Gamma(\alpha)=\int_{0}^{\infty}x^{\alpha-1}\mathrm{e}^{-x}\:\mathrm{d} x,\quad\mbox{for }\alpha > 0.
\end{equation}

#+latex: \begin{fact}
Properties of the Gamma Function:
- \(\Gamma(\alpha)=(\alpha - 1)\Gamma(\alpha - 1)\) for any \(\alpha > 1\), and so \(\Gamma(n)=(n-1)!\) for any positive integer \(n\).
- \(\Gamma(1/2)=\sqrt{\pi}\).
#+latex: \end{fact}

** Linear Algebra \label{sec:Linear-Algebra}
*** Matrices
A /matrix/ is an ordered array of numbers or expressions; typically we write \(\mathbf{A}=\begin{pmatrix}a_{ij}\end{pmatrix}\) or \(\mathbf{A}=\begin{bmatrix}a_{ij}\end{bmatrix}\). If \(\mathbf{A}\) has \(m\) rows and \(n\) columns then we write
\begin{equation}
\mathbf{A}_{\mathrm{m}\times\mathrm{n}}=\begin{bmatrix}a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\end{bmatrix}.
\end{equation}
The /identity matrix/ \(\mathbf{I}_{\mathrm{n}\times\mathrm{n}}\) is an \(\mathrm{n}\times\mathrm{n}\) matrix with zeros everywhere except for 1's along the main diagonal: 
\begin{equation}
\mathbf{I}_{\mathrm{n}\times\mathrm{n}}=\begin{bmatrix}1 & 0 & \cdots & 0\\
0 & 1 & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & 1\end{bmatrix}.
\end{equation}
and the matrix with ones everywhere is denoted \(\mathbf{J}_{\mathrm{n}\times\mathrm{n}}\):
\begin{equation}
\mathbf{J}_{\mathrm{n}\times\mathrm{n}}=\begin{bmatrix}1 & 1 & \cdots & 1\\
1 & 1 & \cdots & 1\\
\vdots & \vdots & \ddots & \vdots\\
1 & 1 & \cdots & 1\end{bmatrix}.
\end{equation}

A /vector/ is a matrix with one of the dimensions equal to one, such as \(\mathbf{A}_{\mathrm{m}\times1}\) (a column vector) or \(\mathbf{A}_{\mathrm{1}\times\mathrm{n}}\) (a row vector). The /zero vector/ \(\mathbf{0}_{\mathrm{n}\times1}\)
is an \(\mathrm{n}\times1\) matrix of zeros:
\begin{equation}
\mathbf{0}_{\mathrm{n}\times1}=\begin{bmatrix}0 & 0 & \cdots & 0\end{bmatrix}^{\mathrm{T}}.
\end{equation}

The /transpose/ of a matrix \(\mathbf{A}=\begin{pmatrix}a_{ij}\end{pmatrix}\) is the matrix \(\mathbf{A}^{\mathrm{T}}=\begin{pmatrix}a_{ji}\end{pmatrix}\), which is just like \(\mathbf{A}\) except the rows are columns and the columns are rows. The matrix \(\mathbf{A}\) is said to be /symmetric/ if \(\mathbf{A}^{\mathrm{T}}=\mathbf{A}\). Note that \(\left(\mathbf{A}\mathbf{B}\right)^{\mathrm{T}}=\mathbf{B}^{\mathrm{T}}\mathbf{A}^{\mathrm{T}}\).

The /trace/ of a square matrix \(\mathbf{A}\) is the sum of its diagonal elements: \(\mathrm{tr}(\mathbf{A})=\sum_{i}a_{ii}\). 

The /inverse/ of a square matrix \(\mathbf{A}_{\mathrm{n}\times\mathrm{n}}\) (when it exists) is the unique matrix denoted \(\mathbf{A}^{-1}\) which satisfies \(\mathbf{A}\mathbf{A}^{-1}=\mathbf{A}^{-1}\mathbf{A}=\mathbf{I}_{\mathrm{n}\times\mathrm{n}}\). If \(\mathbf{A}^{-1}\) exists then we say \(\mathbf{A}\) is /invertible/, or /nonsingular/. Note that \(\left(\mathbf{A}^{\mathrm{T}}\right)^{-1}=\left(\mathbf{A}^{\mathrm{-1}}\right)^{\mathrm{T}}\).
#+latex: \begin{fact}
The inverse of the \(2\times2\) matrix
\begin{equation}
\mathbf{A}=\begin{bmatrix}a & b\\
c & d\end{bmatrix}\quad\mbox{is}\quad\mathbf{A}^{-1}=\frac{1}{ad-bc}\begin{bmatrix}d & -b\\
-c & a\end{bmatrix},
\end{equation}
provided \(ad-bc\neq0\).
#+latex: \end{fact}

*** Determinants
#+latex: \begin{defn}
The /determinant/ of a square matrix \(\mathbf{A}_{\mathrm{n}\times n}\) is denoted \(\mathrm{det}(\mathbf{A})\) or \(|\mathbf{A}|\) and is defined recursively by
\begin{equation}
\mathrm{det}(\mathbf{A})=\sum_{i=1}^{n}(-1)^{i+j}a_{ij}\,\mathrm{det}(\mathbf{M}_{ij}),
\end{equation}
where \(\mathbf{M}_{ij}\) is the submatrix formed by deleting the \(i^{\mathrm{th}}\) row and \(j^{\mathrm{th}}\) column of \(\mathbf{A}\). We may choose any fixed \(1\leq j\leq n\) we wish to compute the determinant; the final result is independent of the \(j\) chosen.
#+latex: \end{defn}
#+latex: \begin{fact}
The determinant of the \(2\times2\) matrix
\begin{equation}
\mathbf{A}=\begin{bmatrix}a & b\\
c & d\end{bmatrix}\quad\mbox{is}\quad|\mathbf{A}|=ad-bc.
\end{equation}
#+latex: \end{fact}

#+latex: \begin{fact}
A square matrix \(\mathbf{A}\) is nonsingular if and only if \(\mathrm{det}(\mathbf{A})\neq0\).
#+latex: \end{fact}

*** Positive (Semi)Definite
If the matrix \(\mathbf{A}\) satisfies \(\mathbf{x^{\mathrm{T}}}\mathbf{A}\mathbf{x}\geq0\) for all vectors \(\mathbf{x}\neq\mathbf{0}\), then we say that \(\mathbf{A}\) is /positive semidefinite/. If strict inequality holds for all \(\mathbf{x}\neq\mathbf{0}\), then \(\mathbf{A}\) is /positive definite/. The connection to statistics is that covariance matrices (see Chapter \ref{cha:Multivariable-Distributions}) are always positive semidefinite, and many of them are even positive definite.

** Multivariable Calculus \label{sec:Multivariable-Calculus}
*** Partial Derivatives
If \(f\) is a function of two variables, its /first-order partial derivatives/ are defined by
\begin{equation}
\frac{\partial f}{\partial x}=\frac{\partial}{\partial x}f(x,y)=\lim_{h\to0}\frac{f(x+h,\, y)-f(x,y)}{h}
\end{equation}
and
\begin{equation}
\frac{\partial f}{\partial y}=\frac{\partial}{\partial y}f(x,y)=\lim_{h\to0}\frac{f(x,\, y+h)-f(x,y)}{h},
\end{equation}
provided these limits exist. The /second-order partial derivatives/ of \(f\) are defined by
\begin{equation}
\frac{\partial^{2}f}{\partial x^{2}}=\frac{\partial}{\partial x}\left(\frac{\partial f}{\partial x}\right),\quad\frac{\partial^{2}f}{\partial y^{2}}=\frac{\partial}{\partial y}\left(\frac{\partial f}{\partial y}\right),\quad\frac{\partial^{2}f}{\partial x\partial y}=\frac{\partial}{\partial x}\left(\frac{\partial f}{\partial y}\right),\quad\frac{\partial^{2}f}{\partial y\partial x}=\frac{\partial}{\partial y}\left(\frac{\partial f}{\partial x}\right).
\end{equation}
In many cases (and for all cases in this book) it is true that
\begin{equation}
\frac{\partial^{2}f}{\partial x\partial y}=\frac{\partial^{2}f}{\partial y\partial x}.
\end{equation}

*** Optimization
An function \(f\) of two variables has a /local maximum/ at \((a,b)\) if \(f(x,y)\geq f(a,b)\) for all points \((x,y)\) near \((a,b)\), that is, for all points in an open disk centered at \((a,b)\). The number \(f(a,b)\) is then called a /local maximum value/ of \(f\). The function \(f\) has a /local minimum/ if the same thing happens with the inequality reversed.

Suppose the point \((a,b)\) is a /critical point/ of \(f\), that is, suppose \((a,b)\) satisfies 
\begin{equation}
\frac{\partial f}{\partial x}(a,b)=\frac{\partial f}{\partial y}(a,b)=0.
\end{equation}
Further suppose \(\frac{\partial^{2}f}{\partial x^{2}}\) and \(\frac{\partial^{2}f}{\partial y^{2}}\) are continuous near \((a,b)\). Let the /Hessian matrix/ \(H\) (not to be confused with the /hat matrix/ \(\mathbf{H}\) of Chapter \ref{cha:multiple-linear-regression}) be defined by
\begin{equation}
H = 
\begin{bmatrix}
\frac{\partial^{2}f}{\partial x^{2}} & \frac{\partial^{2}f}{\partial x\partial y}\\
\frac{\partial^{2}f}{\partial y\partial x} & \frac{\partial^{2}f}{\partial y^{2}}
\end{bmatrix}.
\end{equation}
We use the following rules to decide whether \((a,b)\) is an /extremum/ (that is, a local minimum or local maximum) of \(f\).
- If \(\mbox{det}(H)>0\) and \(\frac{\partial^{2}f}{\partial x^{2}}(a,b)>0\), then \((a,b)\) is a local minimum of \(f\).
- If \(\mbox{det}(H)>0\) and \(\frac{\partial^{2}f}{\partial x^{2}}(a,b)<0\), then \((a,b)\) is a local maximum of \(f\).
- If \(\mbox{det}(H)<0\), then \((a,b)\) is a /saddle point/ of \(f\) and so is not an extremum of \(f\).
- If \(\mbox{det}(H)=0\), then we do not know the status of \((a,b)\); it might be an extremum or it might not be.


*** Double and Multiple Integrals
Let \(f\) be defined on a rectangle \(R=[a,b]\times[c,d]\), and for each \(m\) and \(n\) divide \([a,b]\) (respectively \([c,d]\)) into subintervals \([x_{j},x_{j+1}]\), \(i=0,1,\ldots,m-1\) (respectively \([y_{i},y_{i+1}]\)) of length \(\Delta x_{j}=(b-a)/m\) (respectively \(\Delta y_{i}=(d-c)/n\)) where \(x_{0}=a\) and \(x_{m}=b\) (and \(y_{0}=c\) and \(y_{n}=d\) ), and let \(x_{j}^{\ast}\) (\(y_{i}^{\ast}\)) be any points chosen from their respective subintervals. Then the /double integral/ of \(f\) over the rectangle \(R\) is
\begin{equation}
\iintop_{R}f(x,y)\,\mathrm{d} A=\intop_{c}^{d}\!\!\!\intop_{a}^{b}f(x,y)\,\mathrm{d} x\mathrm{d} y=\lim_{m,n\to\infty}\sum_{i=1}^{n}\sum_{j=1}^{m}f(x_{j}^{\ast},y_{i}^{\ast})\Delta x_{j}\Delta y_{i},
\end{equation}
provided this limit exists. Multiple integrals are defined in the same way just with more letters and sums.


*** Bivariate and Multivariate Change of Variables
Suppose we have a transformation
#+latex: \footnote{For our purposes \(T\) is in fact the /inverse/ of a one-to-one transformation that we are initially given. We usually start with functions that map \((x,y) \longmapsto (u,v)\), and one of our first tasks is to solve for the inverse transformation that maps \((u,v)\longmapsto(x,y)\). It is this inverse transformation which we are calling \(T\).}
\(T\) that maps points \((u,v)\) in a set \(A\) to points \((x,y)\) in a set \(B\). We typically write \(x=x(u,v)\) and \(y=y(u,v)\), and we assume that \(x\) and \(y\) have continuous first-order partial derivatives. We say that \(T\) is /one-to-one/ if no two distinct \((u,v)\) pairs get mapped to the same \((x,y)\) pair; in this book, all of our multivariate transformations \(T\) are one-to-one.

The /Jacobian/ (pronounced ``yah-KOH-bee-uhn'') of \(T\) is denoted by \(\partial(x,y)/\partial(u,v)\) and is defined by the determinant of the following matrix of partial derivatives:
\begin{equation}
\frac{\partial(x,y)}{\partial(u,v)}=\left|
\begin{array}{cc}
\frac{\partial x}{\partial u} & \frac{\partial x}{\partial v}\\
\frac{\partial y}{\partial u} & \frac{\partial y}{\partial v}
\end{array}
\right|=\frac{\partial x}{\partial u}\frac{\partial y}{\partial v}-\frac{\partial x}{\partial v}\frac{\partial y}{\partial u}.
\end{equation}

If the function \(f\) is continuous on \(A\) and if the Jacobian of \(T\) is nonzero except perhaps on the boundary of \(A\), then 
\begin{equation}
\iint_{B}f(x,y)\,\mathrm{d} x\,\mathrm{d} y=\iint_{A}f\left[x(u,v),\, y(u,v)\right]\ \left|\frac{\partial(x,y)}{\partial(u,v)}\right|\mathrm{d} u\,\mathrm{d} v.
\end{equation} 

A multivariate change of variables is defined in an analogous way: the one-to-one transformation \(T\) maps points \((u_{1},u_{2},\ldots,u_{n})\) to points \((x_{1},x_{2},\ldots,x_{n})\), the Jacobian is the determinant of the \(\mathrm{n}\times\mathrm{n}\) matrix of first-order partial derivatives of \(T\) (lined up in the natural manner), and instead of a double integral we have a multiple integral over multidimensional sets \(A\) and \(B\).

* Writing Reports with \textsf{R}
\label{cha:Writing-Reports-with}

Perhaps the most important part of a statistician's job once the analysis is complete is to communicate the results to others. This is usually done with some type of report that is delivered to the client, manager, or administrator. Other situations that call for reports include term papers, final projects, thesis work, /etc/. This chapter is designed to pass along some tips about writing reports once the work is completed with \textsf{R}.


** What to Write \label{sec:What-to-Write}
It is possible to summarize this entire appendix with only one sentence: /the statistician's goal is to communicate with others/. To this end, there are some general guidelines that I give to students which are based on an outline originally written and shared with me by Dr.~G.~Andy Chang.

*** Basic Outline for a Statistical Report
1. Executive Summary (a one page description of the study and conclusion) 
1. Introduction 
   1. What is the question, and why is it important?
   1. Is the study observational or experimental?
   1. What are the hypotheses of interest to the researcher?
   1. What are the types of analyses employed? (one sample \(t\)-test, paired-sample \(t\)-test, ANOVA, chi-square test, regression, ...) 
1. Data Collection 
   1. Describe how the data were collected in detail.
   1. Identify all variable types: quantitative, qualitative, ordered or nominal (with levels), discrete, continuous.
   1. Discuss any limitations of the data collection procedure. Look carefully for any sources of bias.
1. Summary Information
   1. Give numeric summaries of all variables of interest.
      1. Discrete: (relative) frequencies, contingency tables, odds ratios, /etc/. 
      1. Continuous: measures of center, spread, shape.
   1. Give visual summaries of all variables of interest.
      1. Side-by-side boxplots, scatterplots, histograms, /etc/.
   1. Discuss any unusual features of the data (outliers, clusters, granularity, /etc/.)
   1. Report any missing data and identify any potential problems or bias.
1. Analysis 
   1. State any hypotheses employed, and check the assumptions. 
   1. Report test statistics, /p/-values, and confidence intervals. 
   1. Interpret the results in the context of the study.
   1. Attach (labeled) tables and/or graphs and make reference to them in the report as needed. 
1. Conclusion
   1. Summarize the results of the study. What did you learn? 
   1. Discuss any limitations of the study or inferences.
   1. Discuss avenues of future research suggested by the study. 

** How to Write It with R \label{sec:How-to-Write}
Once the decision has been made what to write, the next task is to typeset the information to be shared. To do this the author will need to select software to use to write the documents. There are many options available, and choosing one over another is sometimes a matter of taste. But not all software were created equal, and \textsf{R} plays better with some applications than it does with others. 
In short, \textsf{R} does great with \LaTeX{} and there are many resources available to make writing a document with \textsf{R} and \LaTeX{} easier. But \LaTeX{} is not for the beginner, and there are other word processors which may be acceptable depending on the circumstances.


*** Microsoft\(\circledR\) Word
It is a fact of life that Microsoft\(\circledR\) Windows is currently the most prevalent desktop operating system on the planet. Those who own Windows also typically own some version of Microsoft Office, thus Microsoft Word is the default word processor for many, many people.  

The standard way to write an \textsf{R} report with Microsoft\(\circledR\) Word is to generate material with \textsf{R} and then copy-paste the material at selected places in a Word document. An advantage to this approach is that Word is nicely designed to make it easy to copy-and-paste from \textsf{RGui} to the Word document.

A disadvantage to this approach is that the R input/output needs to be edited manually by the author to make it readable for others. Another disadvantage is that the approach does not work on all operating systems (not on Linux, in particular). Yet another disadvantage is that Microsoft\(\circledR\) Word is proprietary, and as a result, \textsf{R} does not communicate with Microsoft\(\circledR\) Word as well as it does with other software as we shall soon see.

Nevertheless, if you are going to write a report with Word there are some steps that you can take to make the report more amenable to the reader. 

1. Copy and paste graphs into the document. You can do this by right clicking on the graph and selecting \textsf{Copy as bitmap,} or \textsf{Copy as metafile}, or one of the other options. Then move the cursor to the document where you want the picture, right-click, and select \textsf{Paste}.
1. Resize (most) pictures so that they take up no more than 1/2 page. You may want to put graphs side by side; do this by inserting a table and placing the graphs inside the cells.
1. Copy selected \textsf{R} input and output to the Word document. All code should be separated from the rest of the writing, except when specifically mentioning a function or object in a sentence.
1. The font of \textsf{R} input/output should be Courier New, or some other monowidth font (not Times New Roman or Calibri); the default font size of =12= is usually too big for \textsf{R} code and should be reduced to, for example, =10pt=.

It is also possible to communicate with \textsf{R} through OpenOffice.org, which can export to the proprietary (=.doc=) format.


*** OpenOffice.org and \texttt{odfWeave}
OpenOffice.org (OO.o) is an open source desktop productivity suite which mirrors Microsoft\(\circledR\) Office. It is especially nice because it works on all operating systems. OO.o can read most document formats, and in particular, it will read =.doc= files. The standard OO.o file extension for documents is =.odt=, which stands for ``open document text''.

The =odfWeave=  package \cite{odfweave} provides a way to generate an =.odt= file with \textsf{R} input and output code formatted correctly and inserted in the correct places, without any additional work. In this way, one does not need to worry about all of the trouble of typesetting \textsf{R} output. Another advantage of =odfWeave= is that it allows you to generate the report dynamically; if the data underlying the report change or are updated, then a few clicks (or commands) will generate a brand new report.

One disadvantage is that the source =.odt=  file is not easy to read, because it is difficult to visually distinguish the noweb parts (where the \textsf{R} code is) from the non-noweb parts. This can be fixed by manually changing the font of the noweb sections to, for instance, Courier font, size =10pt=. But it is extra work. It would be nice if a program would discriminate between the two different sections and automatically typeset the respective parts in their correct fonts. This is one of the advantages to \LyX{}.

Another advantage of OO.o is that even after you have generated the outfile, it is fully editable just like any other =.odt= document. If there are errors or formatting problems, they can be fixed at any time.

Here are the basic steps to typeset a statistical report with OO.o.

1. Write your report as an =.odt= document in OO.o just as you would any other document. Call this document =infile.odt=, and make sure that it is saved in your working directory. 
1. At the places you would like to insert \textsf{R} code in the document, write the code chunks in the following format:
   \texttt{<\textcompwordmark{}<>\textcompwordmark{}>=}~\\
   \texttt{x <- rnorm(10)}~\\
   \texttt{mean(x)}~\\
   \texttt{@}
   or write whatever code you want between the symbols \texttt{<\textcompwordmark{}<>\textcompwordmark{}>=} and \texttt{@}.
1. Open \textsf{R} and type the following:
   #+begin_src R :exports code :eval never
   library(odfWeave)
   odfWeave(file = "infile.odt", dest = "outfile.odt")
   #+end_src
1. The compiled (=.odt=) file, complete with all of the \textsf{R} output automatically inserted in the correct places, will now be the file =outfile.odt= located in the working directory. Open =outfile.odt=, examine it, modify it, and repeat if desired. 

There are all sorts of extra things that you can do. For example, the \textsf{R} commands can be suppressed with the tag \texttt{<\textcompwordmark{}<echo = FALSE>\textcompwordmark{}>=}, and the \textsf{R} output may be hidden with \texttt{<\textcompwordmark{}<results = hide>\textcompwordmark{}>=}. See the =odfWeave= package documentation for details.

*** Sweave and \protect\LaTeX{}

This approach is nice because it works for all operating systems. One can quite literally typeset /anything/ with \LaTeX{}. All of this power comes at a price, however. The writer must learn the \LaTeX{} language which is a nontrivial enterprise. Even given the language, if there is a single syntax error, or a single delimeter missing in the entire document, then the whole thing breaks.

\LaTeX{} can do anything, but it is relatively difficult to learn  and very grumpy about syntax errors and delimiter matching. There are however programs useful for formatting LaTeX.

A disadvantage is that you cannot see the mathematical formulas until you run the whole file with \LaTeX{}.

A disadvantage is that figures and tables are relatively difficult.

There are programs to make the process easier: AUC\TeX{}.

dev.copy2eps, also dev.copy2pdf

\url{http://www.stat.uni-muenchen.de/~leisch/Sweave/}


*** Sweave and \protect\LyX{}
This approach is nice because it works for all operating  systems. It gives you everything from the last section and makes it easier to use \LaTeX{}. That being said, it is better to know \LaTeX{} already when migrating to \LyX{}, because you understand all of the machinery going on under the hood.

Program Listings and the \textsf{R} language
\url{http://gregor.gorjanc.googlepages.com/lyx-sweave}


** Formatting Tables \label{sec:Formatting-Tables}

The prettyR package 

The Hmisc package

#+begin_src R :exports both :results output pp 
library(Hmisc)
summary(cbind(Sepal.Length, Sepal.Width) ~ Species, data = iris)
#+end_src

#+results[0b0ddb8f7dfbc5175a5aff3c39c7105f5d778950]:
#+begin_example
cbind(Sepal.Length, Sepal.Width)    N=150
-------+----------+---+------------+-----------+
|       |          |N  |Sepal.Length|Sepal.Width|
-------+----------+---+------------+-----------+
|Species|setosa    | 50|5.006000    |3.428000   |
|       |versicolor| 50|5.936000    |2.770000   |
|       |virginica | 50|6.588000    |2.974000   |
-------+----------+---+------------+-----------+
|Overall|          |150|5.843333    |3.057333   |
-------+----------+---+------------+-----------+
#+end_example

There is a =method= argument to =summary=, which is set to \texttt{method = "response"} by default. There are two other methods for summarizing data: =reverse= and =cross=. See =?summary.formula= or the following document from Frank Harrell for more details \url{http://biostat.mc.vanderbilt.edu/twiki/bin/view/Main/StatReport}.


** Other Formats \label{sec:Other-Formats}

HTML and prettyR
R2HTML

* Instructions for Instructors
\label{cha:Instructions-for-Instructors}

\noun{WARNING: this appendix is not applicable until the exercises
have been written.} 
#+begin_src R :exports none
set.seed(095259)
#+end_src

#+results[ce382389430c46506972e5b1bdefa6fe10c4820a]:

Probably this /book/ could more accurately be described as /software/. The reason is that the document is one big random variable, one observation realized out of millions. It is electronically distributed under the GNU FDL, and ``free'' in both senses: speech and beer.  

There are four components to \IPSUR: the Document, the Program used to generate it, the \textsf{R} package that holds the Program, and the Ancillaries that accompany it.

The majority of the data and exercises have been designed to be randomly generated. Different realizations of this book will have different graphs and exercises throughout. The advantage of this approach is that a teacher, say, can generate a unique version to be used in his/her class. Students can do the exercises and the teacher will have the answers to all of the problems in their own, unique solutions manual. Students may download a different solutions manual online somewhere else, but none of the answers will match the teacher's copy. 

Then next semester, the teacher can generate a /new/ book and the problems will be more or less identical, except the numbers will be changed. This means that students from different sections of the same class will not be able to copy from one another quite so easily. The same will be true for similar classes at different institutions. Indeed, as long as the instructor protects his/her /key/ used to generate the book, it will be difficult for students to crack the code. And if they are industrious enough at this level to find a way to (a) download and decipher my version's source code, (b) hack the teacher's password somehow, and (c) generate the teacher's book with all of the answers, then they probably should be testing out of an ``Introduction to Probability and Statistics'' course, anyway. 

The book that you are reading was created with a random seed which was set at the beginning. The original seed is 42. You can choose your own seed, and generate a new book with brand new data for the text and exercises, complete with updated manuals. A method I recommend for finding a seed is to look down at your watch at this very moment and record the 6 digit hour, minute, and second (say, 9:52:59am): choose that for a seed
#+latex: \footnote{In fact, this is essentially the method used by \textsf{R} to select an initial random seed, see =?set.seed=. However, the instructor should set the seed manually so that the book can be regenerated at a later time, if necessary.}.
This method already provides for over 43,000 books, without taking military time into account. An alternative would be to go to \textsf{R} and type 

#+begin_src R
options(digits = 16)
runif(1)
#+end_src

Now choose \( SRC_R{set.seed(095259); options(digits = 16); runif(1)*10^16} \)as your secret seed... write it down in a safe place and do not share it with anyone. Next generate the book with your seed using \LyX{}-Sweave or Sweave-\LaTeX{}. You may wish to also generate Student and Instructor Solution Manuals. Guidance regarding this is given below in the How to Use This Document section.

** Generating This Document \label{sec:Generating-This-Document}

You will need three (3) things to generate this document for yourself, in addition to a current \textsf{R} distribution which at the time of this writing is \texttt{ SRC_R{version$version.string} } :
1. a LaTeX distribution,
2. Sweave (which comes with \textsf{R} automatically), and 
3. \LyX (optional, but recommended).

We will discuss each of these in turn.

- LaTeX: ::  The distribution used by the present author was \TeX{} Live (\url{http://www.tug.org/texlive/}). There are plenty of other perfectly suitable LaTeX distributions depending on your operating system, one such alternative being MikTeX (\url{http://miktex.org/}) for Microsoft Windows. 
- Sweave: :: If you have \textsf{R} installed, then the required Sweave files are already on your system... somewhere. The only problems that you may have are likely associated with making sure that your LaTeX distribution knows where to find the =Sweave.sty= file. See the Sweave Homepage (\url{http://www.statistik.lmu.de/~leisch/Sweave/}) for guidance on how to get it working on your particular operating system.
- LyX: :: Strictly speaking, LyX is not needed to generate this document. But this document was written stem to stern with LyX, taking full advantage of all of the bells and whistles that LyX has to offer over plain \LaTeX{} editors. And it's free. See the LyX homepage (\url{http://www.lyx.org/}) for additional information. If you decide to give LyX a try, then you will need to complete some extra steps to coordinate Sweave and LyX with each other. Luckily, Gregor Gorjanc has a website and an \textsf{R} News article \cite{Gorjanc2008} to help you do exactly that. See the LyX-Sweave homepage (\url{http://gregor.gorjanc.googlepages.com/lyx-sweave}) for details.

An attempt was made to not be extravagant with fonts or packages so that a person would not need the entire =CTAN= (or =CRAN=) installed on their personal computer to generate the book. Nevertheless, there are a few extra packages required. These packages are listed in the =preamble= of =IPSUR.Rnw=, =IPSUR.tex=, and =IPSUR.lyx=.


** How to Use This Document \label{sec:How-to-Use-Document}

The easiest way to use this document is to install the =IPSUR= package from =CRAN= and be all done. This way would be acceptable if there is another, primary, text being used for the course and \IPSUR\ is only meant to play a supplementary role.

If you plan for \IPSUR\ to serve as the primary text for your course, then it would be wise to generate your own version of the document. You will need the source code for the Program which can be downloaded from =CRAN= or the \IPSUR\ website. Once the source is obtained there are four (4) basic steps to generating your own copy.

1. Randomly select a secret ``seed'' of integers and replace my seed of 42 with your own seed. 
1. Make sure that the \textsf{\textbf{maintext}} branch is turned \textsf{ON} and also make sure that both the \textsf{\textbf{solutions}} branch and the \textsf{\textbf{answers}} branch are turned \textsf{OFF}. Use \LyX{} or your \LaTeX{} editor with Sweave to generate your unique PDF copy of the book and distribute this copy to your students. (See the \LyX{} User's Guide to learn more about branches; the ones referenced above can be found under \textsf{Document \(\triangleright\) Settings \(\triangleright\) Branches}.)
1. Turn the \textsf{\textbf{maintext}} branch \textsf{OFF} and the \textsf{\textbf{solutions}} branch \textsf{ON}. Generate a ``Student Solutions Manual'' which has complete solutions to selected exercises and distribute the PDF to the students. 
1. Leave the \textsf{\textbf{solutions}} branch \textsf{ON} and also turn the \textsf{\textbf{answers}} branch \textsf{ON} and generate an ``Instructor Solutions and Answers Manual'' with full solutions to some of the exercises and just answers to the remaining exercises. Do NOT distribute this to the students -- unless of course you want them to have the answers to all of the problems.  

To make it easier for those people who do not want to use \LyX{} (or for whatever reason cannot get it working), I have included three (3) Sweave files corresponding to the main text, student solutions, and instructor answers, that are included in the \IPSUR\ source package in the \texttt{/tex} subdirectory. In principle it is possible to change the seed and generate the three parts separately with only Sweave and \LaTeX{}. This method is not recommended by me, but is perhaps desirable for some people.

#+latex: \paragraph*{Generating Quizzes and Exams}
- You can copy-paste selected exercises from the text, put them together, and you have a quiz. Since the numbers are randomly generated you do not need to worry about different semesters. And you will have answer keys already for all of your QUIZZES and EXAMS, too. 

** Ancillary Materials \label{sec:Ancillary-Materials}
In addition to the main text, student manual, and instructor manual, there are two other ancillaries. IPSUR.R, and IPSUR.RData.

** Modifying This Document \label{sec:Modifying-This-Document}
Since this document is released under the GNU-FDL, you are free to modify this document however you wish (in accordance with the license -- see Appendix \ref{cha:GNU-Free-Documentation}). The immediate benefit of this is that you can generate the book, with brand new problem sets, and distribute it to your students simply as a PDF (in an email, for instance). As long as you distribute less than 100 such /Opaque/ copies, you are not even required by the GNU-FDL to share your /Transparent/ copy (the source code with the secret key) that you used to generate them. Next semester, choose a new key and generate a new copy to be distributed to the new class. 

#+begin_quote
But more generally, if you are not keen on the way I explained (or failed to explain) something, then you are _free_ to rewrite it. If you would like to cover more (or less) material, then you are _free_ to add (or delete) whatever Chapters/Sections/Paragraphs that you wish. And since you have the source code, you do not need to retype the wheel. 
#+end_quote

Some individuals will argue that the nature of a statistics textbook like this one, many of the exercises being randomly generated /by design/, does a disservice to the students because the exercises do not use real-world data. That is a valid criticism... but in my case the benefits outweighed the detriments and I moved forward to incorporate static data sets whenever it was feasible and effective. Frankly, and most humbly, the only response I have for those individuals is: ``Please refer to the preceding paragraph.''

* =RcmdrTestDrive= Story
\label{cha:RcmdrTestDrive-Story}

The goal of =RcmdrTestDrive= was to have a data set sufficiently rich in the types of data represented such that a person could load it into the \textsf{R} Commander and be able to explore all of =Rcmdr='s menu options at once. I decided early-on that an efficient way to do this would be to generate the data set randomly, and later add to the list of variables as more =Rcmdr= menu options became available. Generating the data was easy, but generating a story that related all of the respective variables proved to be less so.

In the Summer of 2006 I gave a version of the raw data and variable names to my STAT 3743 Probability and Statistics class and invited each of them to write a short story linking all of the variables together in a coherent narrative. No further direction was given. 

The most colorful of those I received was written by Jeffery Cornfield, submitted July 12, 2006, and is included below with his permission. It was edited slightly by the present author and updated to respond dynamically to the random generation of =RcmdrTestDrive=; otherwise, the story has been unchanged. 

** Case File: ALU-179 ``Murder Madness in Toon Town
#+begin_quote
\noindent \begin{center}
*WARNING* 
\par\end{center}
\noindent This file is not for the faint of heart, dear reader, because it is filled with horrible images that will haunt your nightmares. If you are weak of stomach, have irritable bowel syndrome, or are simply paranoid, DO NOT READ FURTHER! Otherwise, read at your own risk.
#+end_quote

One fine sunny day, Police Chief R. Runner called up the forensics department at Acme-Looney University. There had been \( SRC_R{dim(RcmdrTestDrive)[ 1 ] - 2} \) murders in the past \( SRC_R{round((dim(RcmdrTestDrive)[ 1 ] - 2)/24)} \) days, approximately one murder every hour, of many of the local Human workers, shop keepers, and residents of Toon Town. These alarming rates threatened to destroy the fragile balance of Toon and Human camaraderie that had developed in Toon Town. 

Professor Twee T.~Bird, a world-renowned forensics specialist and a Czechoslovakian native, received the call. Professor, we need your expertise in this field to identify the pattern of the killer or killers, Chief Runner exclaimed. We need to establish a link between these people to stop this massacre. 

Yes, Chief Runner, please give me the details of the case, Professor Bird declared with a heavy native accent, (though, for the sake of the case file, reader, I have decided to leave out the accent due to the fact that it would obviously drive you -- if you will forgive the pun -- looney!) 

All prints are wiped clean and there are no identifiable marks on the bodies of the victims. All we are able to come up with is the possibility that perhaps there is some kind of alternative method of which we are unaware. We have sent a secure e-mail with a listing of all of the victims =races=, =genders=, locations of the bodies, and the sequential =order= in which they were killed. We have also included other information that might be helpful, said Chief Runner.

Thank you very much. Perhaps I will contact my colleague in the Statistics Department here, Dr.~Elmer Fudd-Einstein, exclaimed Professor Bird. He might be able to identify a pattern of attack with mathematics and statistics.

Good luck trying to find him, Professor. Last I heard, he had a bottle of scotch and was in the Hundred Acre Woods hunting rabbits, Chief Runner declared in a manner that questioned the beloved doctors credibility. 

Perhaps I will take a drive to find him. The fresh air will do me good.

#+begin_quote
\noindent I will skip ahead, dear reader, for much occurred during this time. Needless to say, after a fierce battle with a mountain cat that the Toon-ology Department tagged earlier in the year as Sylvester, Professor Bird found Dr.~Fudd-Einstein and brought him back, with much bribery of alcohol and the promise of the future slaying of those wascally wabbits (it would help to explain that Dr.~Fudd-Einstein had a speech impediment which was only worsened during the consumption of alcohol.)
#+end_quote

Once our two heroes returned to the beautiful Acme-Looney University, and once Dr.~Fudd-Einstein became sober and coherent, they set off to examine the case and begin solving these mysterious murders.

First off, Dr.~Fudd-Einstein explained, these people all worked at the University at some point or another. Also, there also seems to be a trend in the fact that they all had a =salary= between \( SRC_R{round(min(RcmdrTestDrive$salary))} \) and \( SRC_R{round(max(RcmdrTestDrive$salary))} \) when they retired. 

Thats not really a lot to live off of, explained Professor Bird. 

Yes, but you forget that the Looney Currency System works differently than the rest of the American Currency System. One Looney is equivalent to Ten American Dollars. Also, these faculty members are the ones who faced a cut in their salary, as denoted by =reduction=. Some of them dropped quite substantially when the University had to fix that little /faux pas/ in the Chemistry Department. You remember: when Dr.~D.~Duck tried to create that Everlasting Elixir? As a result, these faculty left the university. Speaking of which, when is his memorial service? inquired Dr.~Fudd-Einstein. 

This coming Monday. But if there were all of these killings, how in the world could one person do it? It just doesnt seem to be possible; stay up \( SRC_R{round((dim(RcmdrTestDrive)[ 1 ] - 2)/24)} \) days straight and be able to kill all of these people and have the energy to continue on, Professor Bird exclaimed, doubting the guilt of only one person. 

Perhaps then, it was a group of people, perhaps there was more than one killer placed throughout Toon Town to commit these crimes. If I feed in these variables, along with any others that might have a pattern, the Acme Computer will give us an accurate reading of suspects, with a scant probability of error. As you know, the Acme Computer was developed entirely in house here at Acme-Looney University, Dr.~Fudd-Einstein said as he began feeding the numbers into the massive server. 

Hey, look at this, Professor Bird exclaimed, Whats with this =before= and =after= information? 

Scroll down; it shows it as a note from the coroners office. Apparently Toon Town Coroner Marvin -- that strange fellow from Mars, Pennsylvania -- feels, in his opinion, that given the fact that the cadavers were either =smokers= or non-smokers, and given their personal health, and family medical history, that this was their life expectancy before contact with cigarettes or second-hand smoke and after, Dr.~Fudd-Einstein declared matter-of-factly. 

Well, would race or gender have something to do with it, Elmer? inquired Professor Bird.

Maybe, but I would bet my money on somebody was trying to quiet these faculty before they made a big ruckus about the secret money-laundering of Old Man Acme. You know, most people think that is how the University receives most of its funds, through the mob families out of Chicago. And I would be willing to bet that these faculty figured out the connection and were ready to tell the Looney Police. Dr.~Fudd-Einstein spoke lower, fearing that somebody would overhear their conversation.  

Dr.~Fudd-Einstein then pressed \textsf{Enter} on the keyboard and waited for the results. The massive computer roared to life... and when I say roared, I mean it literally /roared/. All the hidden bells, whistles, and alarm clocks in its secret compartments came out and created such a loud racket that classes across the university had to come to a stand-still until it finished computing. 

Once it was completed, the computer listed 4 names:

#+begin_example
****************************SUSPECTS****************************
- Yosemite Sam (Looney Insane Asylum) 
- Wile~E.~Coyote (deceased) 
- Foghorn~Leghorn (whereabouts unknown) 
- Granny (1313 Mockingbird Lane, Toon Town USA)
#+end_example

Dr.~Fudd-Einstein and Professor Bird looked on in silence. They could not believe their eyes. The greatest computer on the Gulf of Mexico seaboard just released the most obscure results imaginable.

There seems to be a mistake. Perhaps something is off, Professor Bird asked, still unable to believe the results.

Not possible; the Acme Computer takes into account every kind of connection available. It considers affiliations to groups, and affiliations those groups have to other groups. It checks the FBI, CIA, British intelligence, NAACP, AARP, NSA, JAG, TWA, EPA, FDA, USWA, \textsf{R}, MAPLE, SPSS, SAS, and Ben & Jerrys files to identify possible links, creating the most powerful computer in the world... with a tweak of Toon fanaticism, Dr.~Fudd-Einstein proclaimed, being a proud co-founder of the Acme Computer Technology.

Wait a minute, Ben & Jerry? What would eating ice cream have to do with anything? Professor Bird inquired.

It is in the works now, but a few of my fellow statistician colleagues are trying to find a mathematical model to link the type of ice cream consumed to the type of person they might become. Assassins always ate vanilla with chocolate sprinkles, a little known fact they would tell you about Oswald and Booth, Dr.~Fudd-Einstein declared.

Ive heard about this. My forensics graduate students are trying to identify car thieves with either rocky road or mint chocolate chip so far, the pattern is showing a clear trend with chocolate chip, Professor Bird declared. 
Well, what do we know about these suspects, Twee? Dr.~Fudd-Einstein asked.

Yosemite Sam was locked up after trying to rob that bank in the West Borough. Apparently his guns were switched and he was sent the Acme Kids Joke Gun and they blew up in his face. The containers of peroxide they contained turned all of his facial hair red. Some little child is running around Toon Town with a pair of .38s to this day. 

Wile E.~Coyote was that psychopath working for the Yahtzee - the fanatics who believed that Toons were superior to Humans. He strapped sticks of Acme Dynamite to his chest to be a martyr for the cause, but before he got to the middle of Toon Town, this defective TNT blew him up. Not a single other person -- Toon or Human -- was even close.

Foghorn Leghorn is the most infamous Dog Kidnapper of all times. He goes to the homes of prominent Dog citizens and holds one of their relatives for ransom. If they refuse to pay, he sends them to the pound. Either way, theyre sure stuck in the dog house, Professor Bird laughed. Dr.~Fudd-Einstein didnt seem amused, so Professor Bird continued. 

Granny is the most beloved alumnus of Acme-Looney University. She was in the first graduating class and gives graciously each year to the university. Without her continued financial support, we wouldnt have the jobs we do. She worked as a parking attendant at the University lots... wait a minute, take a look at this, Professor Bird said as he scrolled down in the police information. Grannys signature is on each of these faculty members =parking= tickets. Kind of odd, considering the Chief-of-Parking signed each personally. The deceased had from as few as \( SRC_R{min(RcmdrTestDrive$parking)} \) ticket to as many as \( SRC_R{max(RcmdrTestDrive$parking)} \). All tickets were unpaid.

And look at this, Granny married Old Man Acme after graduation. He was a resident of Chicago and rumored to be a consigliere to one of the most prominent crime families in Chicago, the Chuck Jones/Warner Crime Family, Professor Bird read from the screen as a cold feeling of terror rose from the pit of his stomach. 

Say, dont you live at her house? Wow, youre living under the same roof as one of the greatest criminals/murderers of all time! Dr.~Fudd-Einstein said in awe and sarcasm.

I would never have suspected her, but I guess it makes sense. She is older, so she doesnt need near the amount of sleep as a younger person. She has access to all of the vehicles so she can copy license plate numbers and follow them to their houses. She has the finances to pay for this kind of massive campaign on behalf of the Mob, and she hates anyone that even remotely smells like smoke, Professor Bird explained, wishing to have his hit of nicotine at this time.

Well, I guess there is nothing left to do but to call Police Chief Runner and have him arrest her, Dr.~Fudd-Einstein explained as he began dialing. What I cant understand is how in the world the Police Chief sent me all of this information and somehow seemed to screw it up.

What do you mean? inquired Professor Bird.

Well, look here. The data file from the Chief's email shows \( SRC_R{dim(RcmdrTestDrive)[ 1 ]} \) murders, but there have only been \( SRC_R{dim(RcmdrTestDrive)[ 1 ] - 2} \). This doesnt make any sense. Ill have to straighten it out. Hey, wait a minute. Look at this, Person number \( SRC_R{dim(RcmdrTestDrive)[ 1 ] - 1} \) and Person number \( SRC_R{dim(RcmdrTestDrive)[ 1 ]} \) seem to match our stats. But how can that be?

It was at this moment that our two heroes were shot from behind and fell over the computer, dead. The killer hit \textsf{Delete} on the computer and walked out slowly (considering they had arthritis) and cackling loudly in the now quiet computer lab.  

And so, I guess my question to you the reader is, did Granny murder \( SRC_R{dim(RcmdrTestDrive)[ 1 ]} \) people, or did the murderer slip through the cracks of justice? You be the statistician and come to your own conclusion. 

Detective Pyork E. Pig 

: ***End File***

#+latex: \vfill{}

#+begin_latex
\cleardoublepage
\phantomsection
\addcontentsline{toc}{chapter}{\bibname}
\bibliographystyle{plainurl}
\nocite{*}
\bibliography{IPSUR}
\vfill{}
\cleardoublepage
\phantomsection
\addcontentsline{toc}{chapter}{\indexname} 
\printindex{}
#+end_latex

#+begin_src R :eval never 
rm(.Random.seed)
try(dir.create("../../data"), silent = TRUE)
save.image(file = "../../data/IPSUR.RData")
tools::resaveRdaFiles('../../data', compress = 'xz')
Stangle(file="IPSUR.Rnw", output="../IPSUR.R", annotate=TRUE)
#+end_src
\end{document}



