#!/bin/sh
# -*- mode: shell-script -*-
#
# generate figures
#

emacs -Q --batch \
--eval "(progn
(load \"~/git/IPSUR/init-ipsur.el\")
(R)
(find-file \"~/git/ISPUR/IPSUR.org\")
(org-babel-execute-buffer)
(kill-buffer))"
