#+STARTUP: indent
#+TITLE:     An Introduction to Probability and Statistics
#+AUTHOR:    G. Jay Kerns
#+EMAIL:     gkerns@ysu.edu
#+DESCRIPTION: This is a basic introduction to the essential ideas of probability and statistics.
#+KEYWORDS: introduction probability statistics
#+LANGUAGE:  en
#+OPTIONS:   H:4 toc:3 \n:nil @:t ::t |:t ^:{} -:t f:nil *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:nil
#+INFOJS_OPT: view:info toc:nil ftoc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+STYLE: <link rel="stylesheet" type="text/css" href="css/stylesheet.css" />
#+LaTeX_CLASS: scrbook
#+LINK_UP: index.html   
#+LINK_HOME: http://ipsur.org/index.html
#+EXPORT_SELECT_TAGS: introps datadesc
#+BABEL: :session *R* :exports results :results value raw :cache no :tangle yes
#+INCLUDE: "prelim.R" src R :exports none :results hide

* An Introduction to Probability and Statistics                     :introps:
:PROPERTIES:
:tangle: R/introps.R
:END:
#+latex: \pagenumbering{arabic} 

#+latex: \noindent 
This chapter has proved to be the hardest to write, by far. The trouble is that there is so much to say -- and so many people have already said it so much better than I could. When I get something I like I will release it here.

In the meantime, there is a lot of information already available to a person with an Internet connection. I recommend to start at Wikipedia, which is not a flawless resource but it has the main ideas with links to reputable sources.

In my lectures I usually tell stories about Fisher, Galton, Gauss, Laplace, Quetelet, and the Chevalier de Mere.

** Probability

The common folklore is that probability has been around for millennia but did not gain the attention of mathematicians until approximately 1654 when the Chevalier de Mere had a question regarding the fair division of a game's payoff to the two players, if the game had to end prematurely.

Here is a link to Section [[sec:Types-of-Data][hello there again]] in another file, and here is a \ref{sec:Types-of-Data}.  And here is a hyperlink way [[Types of Data][Blah blah data]]

- A link like this will work in both HTML and PDF as long as the link is to a location within the same file (and if I get rid of all the colons in my labels).  [[sec:Types-of-Data][hello there again]]

- The following works for all PDF links, but doesn't work for HTML, regardless of whether or not I get rid of the colons.   \ref{sec:Types-of-Data}

- The following way will work for PDF links, but only for HTML links within the same file.   [[Types of Data][Blah blah data]]

- I'm going to try this way.  I will use the custom ID, and it will link to another headline.  I need to check it for HTML and PDF.  Here is just the heading name, and then  [[Statistics][some crazy text]] and here is the custom id  [[sec-Intro-Statistics][some more crazy text]].  OK, both ways work for HTML; the first way uses the org-mode generated label, but the second uses the custom ID.  Now I will repeat (in HTML) what happens if I don't put in a description.  Here is just the heading name, and then  [[Statistics]] and here is the custom id  [[sec-Intro-Statistics]].  OK, the first of the pair worked in PDF, but not the second.  I suspect it's because of the colon in my custom ID.  I will replace it with a hyphen and try both again.  Alright, I'm getting somewhere.  If I replace the colons with hyphens then both in the pair work everywhere, PDF and HTML.  There's only one more question.  I commented out the export to pdf which replaces hyperrefs with refs.  Let me uncomment that and see what happens. Even more progress.  When I uncomment the conversion, then all of the anchor texts are replaced by section numbers in PDF export, only.  HTML is unchanged.  Last question: what happens if I put an ordinary link in under my current settings?  I think it's going to screw everything up for pdf export.  Let's try it here  [[http://www.google.com][here is a link to google]]

- the following way will work for HTML, even within another file, but on PDF it screws up and shows some local path on my machine. [[file:data-description.org::sec:Types-of-Data][Section]]


It does let's try some math $A$ and $B$

** Statistics
:PROPERTIES:
:CUSTOM_ID: sec-Intro-Statistics
:END:

Statistics concerns data; their collection, analysis, and interpretation. In this book we distinguish between two types of statistics: descriptive and inferential. 

Descriptive statistics concerns the summarization of data. We have a data set and we would like to describe the data set in multiple ways. Usually this entails calculating numbers from the data, called descriptive measures, such as percentages, sums, averages, and so forth.

Inferential statistics does more. There is an inference associated with the data set, a conclusion drawn about the population from which the data originated.

I would like to mention that there are two schools of thought of statistics: frequentist and bayesian. The difference between the schools is related to how the two groups interpret the underlying probability (see Section \ref{sec:Interpreting-Probabilities}). The frequentist school gained a lot of ground among statisticians due in large part to the work of Fisher, Neyman, and Pearson in the early twentieth century. That dominance lasted until inexpensive computing power became widely available; nowadays the bayesian school is garnering more attention and at an increasing rate.

This book is devoted mostly to the frequentist viewpoint because that is how I was trained, with the conspicuous exception of Sections \ref{sec:Bayes'-Rule} and \ref{sec:Conditional-Distributions}. I plan to add more bayesian material in later editions of this book.

#+latex: \newpage{}

** Exercises
#+latex: \setcounter{thm}{0}





