#+STARTUP:   indent
#+TITLE:     An Introduction to Probability and Statistics
#+AUTHOR:    G. Jay Kerns
#+EMAIL:     gkerns@ysu.edu
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:nil *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: answ soln
#+DRAWERS: HIDDEN PROPERTIES STATE PREFACE
#+BABEL: :session *R* :exports results :results value raw replace :cache no :tangle yes
#+LaTeX_CLASS: scrbook
#+LaTeX_CLASS_OPTIONS: [captions=tableheading]
#+LaTeX_CLASS_OPTIONS: [10pt,english]
#+LaTeX_HEADER: \input{preamble}

* An Introduction to Probability and Statistics
\pagenumbering{arabic} 
#+begin_src R :exports none
rm(list = ls())
seed <- 42
set.seed(seed)
options(width = 60)
options(useFancyQuotes = FALSE)
library(actuar)
library(aplpack)
library(boot)
library(coin)
library(combinat)
library(distrEx)
library(e1071)
library(ggplot2)
library(HH)
library(Hmisc)
library(lattice)
library(lmtest)
library(mvtnorm)
library(prob)
library(qcc)
library(RcmdrPlugin.IPSUR)
library(reshape)
library(scatterplot3d)
library(stats4)
library(TeachingDemos)
#+end_src

\noindent This chapter has proved to be the hardest to write, by far. The trouble is that there is so much to say -- and so many people have already said it so much better than I could. When I get something I like I will release it here.

In the meantime, there is a lot of information already available to a person with an Internet connection. I recommend to start at Wikipedia, which is not a flawless resource but it has the main ideas with links to reputable sources.

In my lectures I usually tell stories about Fisher, Galton, Gauss, Laplace, Quetelet, and the Chevalier de Mere.

** Probability

The common folklore is that probability has been around for millennia but did not gain the attention of mathematicians until approximately 1654 when the Chevalier de Mere had a question regarding the fair division of a game's payoff to the two players, if the game had to end prematurely.

** Statistics

Statistics concerns data; their collection, analysis, and interpretation. In this book we distinguish between two types of statistics: descriptive and inferential. 

Descriptive statistics concerns the summarization of data. We have a data set and we would like to describe the data set in multiple ways. Usually this entails calculating numbers from the data, called descriptive measures, such as percentages, sums, averages, and so forth.

Inferential statistics does more. There is an inference associated with the data set, a conclusion drawn about the population from which the data originated.

I would like to mention that there are two schools of thought of statistics: frequentist and bayesian. The difference between the schools is related to how the two groups interpret the underlying probability (see Section \ref{sec:Interpreting-Probabilities}). The frequentist school gained a lot of ground among statisticians due in large part to the work of Fisher, Neyman, and Pearson in the early twentieth century. That dominance lasted until inexpensive computing power became widely available; nowadays the bayesian school is garnering more attention and at an increasing rate.

This book is devoted mostly to the frequentist viewpoint because that is how I was trained, with the conspicuous exception of Sections \ref{sec:Bayes'-Rule} and \ref{sec:Conditional-Distributions}. I plan to add more bayesian material in later editions of this book.

#+begin_latex
\section*{Chapter Exercises}
\addcontentsline{toc}{section}{Chapter Exercises}
\setcounter{thm}{0}
#+end_latex







