#+STARTUP: indent
#+TITLE:     Preface
#+AUTHOR:    G. Jay Kerns
#+EMAIL:     gkerns@ysu.edu
#+DESCRIPTION: This is a preface to IPSUR: Introduction to Probability and Statistics Using R
#+KEYWORDS: preface IPSUR
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:t \n:nil @:t ::t |:t ^:{} -:t f:nil *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   index.html
#+LINK_HOME: http://ipsur.org
#+XSLT:
#+BABEL: :session *R* :exports results :results value raw :cache no :tangle yes
#+INCLUDE: "prelim.R" src R :exports none :results hide

#+BEGIN_HTML
---
layout: chapter
title: Preface
previous: index.html
next: introduction-probability-statistics.html
description: This is a preface to IPSUR: Introduction to Probability and Statistics Using R.
keywords: preface IPSUR
---
#+END_HTML

* Preface


#+latex: \chapter*{Preface}

This book was expanded from lecture materials I use in a one semester upper-division undergraduate course entitled /Probability and Statistics/ at Youngstown State University. Those lecture materials, in turn, were based on notes that I transcribed as a graduate student at Bowling Green State University. The course for which the materials were written is 50-50 Probability and Statistics, and the attendees include mathematics, engineering, and computer science majors (among others). The catalog prerequisites for the course are a full year of calculus.

The book can be subdivided into three basic parts. The first part includes the introductions and elementary /descriptive statistics/; I want the students to be knee-deep in data right out of the gate. The second part is the study of /probability/, which begins at the basics of sets and the equally likely model, journeys past discrete/continuous  random variables, and continues through to multivariate distributions. The chapter on sampling distributions paves the way to the third part, which is /inferential statistics/. This last part includes point and interval estimation, hypothesis testing, and finishes with introductions to selected topics in applied statistics.

I usually only have time in one semester to cover a small subset of this book. I cover the material in Chapter 2 in a class period that is supplemented by a take-home assignment for the students. I spend a lot of time on Data Description, Probability, Discrete, and Continuous Distributions. I mention selected facts from Multivariate Distributions in passing, and discuss the meaty parts of Sampling Distributions before moving right along to Estimation (which is another chapter I dwell on considerably). Hypothesis Testing goes faster after all of the previous work, and by that time the end of the semester is in sight. I normally choose one or two final chapters (sometimes three) from the remaining to survey, and regret at the end that I did not have the chance to cover more.

In an attempt to be correct I have included material in this book which I would normally not mention during the course of a standard lecture. For instance, I normally do not highlight the intricacies of measure theory or integrability conditions when speaking to the class. Moreover, I often stray from the matrix approach to multiple linear regression because many of my students have not yet been formally trained in linear algebra. That being said, it is important to me for the students to hold something in their hands which acknowledges the world of mathematics and statistics beyond the classroom, and which may be useful to them for many semesters to come. It also mirrors my own experience as a student.

The vision for this document is a more or less self contained, essentially complete, correct, introductory textbook. There should be plenty of exercises for the student, with full solutions for some, and no solutions for others (so that the instructor may assign them for grading). By =Sweave='s dynamic nature it is possible to write randomly generated exercises and I had planned to implement this idea already throughout the book. Alas, there are only 24 hours in a day. Look for more in future editions.

Seasoned readers will be able to detect my origins: /Probability and Statistical Inference/ by Hogg and Tanis \cite{Hogg2006}, /Statistical Inference/ by Casella and Berger \cite{Casella2002}, and /Theory of Point Estimation/ and /Testing Statistical Hypotheses/ by Lehmann \cite{Lehmann1998,Lehmann1986}. I highly recommend each of those books to every reader of this one. Some \textsf{R} books with ``introductory'' in the title that I recommend are /Introductory Statistics with R/ 
by Dalgaard \cite{Dalgaard2008} and /Using R for Introductory Statistics/ by Verzani \cite{Verzani2005}. Surely there are many, many other good introductory books about \textsf{R}, but frankly, I have tried to steer clear of them for the past year or so to avoid any undue influence on my own writing.

I would like to make special mention of two other books: /Introduction to Statistical Thought/ by Michael Lavine \cite{Lavine2009} and /Introduction to Probability/ by Grinstead and Snell \cite{Grinstead1997}. Both of these books are /free/ and are what ultimately convinced me to release \IPSUR under a free license, too.

Please bear in mind that the title of this book is ``Introduction to Probability and Statistics Using \textsf{R}'', and not ``Introduction to \textsf{R} Using Probability and Statistics'', nor even ``Introduction to Probability and Statistics and \textsf{R} Using Words''. The people at the party are Probability and Statistics; the handshake is \textsf{R}. There are several important topics about \textsf{R} which some individuals will feel are underdeveloped, glossed over, or wantonly omitted. Some will feel the same way about the probabilistic and/or statistical content. Still others will just want to learn \textsf{R} and skip all of the mathematics.

Despite any misgivings: here it is, warts and all. I humbly invite said individuals to take this book, with the GNU Free Documentation License (GNU-FDL) in hand, and make it better. In that spirit there are at least a few ways in my view in which this book could be improved.

- Better data. :: The data analyzed in this book are almost entirely from the =datasets= package in base \textsf{R}, and here is why:

  - I made a conscious effort to minimize dependence on contributed packages,

  - The data are instantly available, already in the correct format, so we need not take time to manage them, and 

  - The data are /real/.

I made no attempt to choose data sets that would be interesting to the students; rather, data were chosen for their potential to convey a statistical point. Many of the data sets are decades old or more (for instance, the data used to introduce simple linear regression are the speeds and stopping distances of cars in the 1920's).

In a perfect world with infinite time I would research and contribute recent, /real/ data in a context crafted to engage the students in /every/ example. One day I hope to stumble over said time. In the meantime, I will add new data sets incrementally as time permits.

- More proofs. :: I would like to include more proofs for the sake of completeness (I understand that some people would not consider more proofs to be improvement). Many proofs have been skipped entirely, and I am not aware of any rhyme or reason to the current omissions. I will add more when I get a chance.  

- More and better~graphics. :: I have not used the =ggplot2= package \cite{Wickam2009} because I do not know how to use it yet. It is on my to-do list.

- More and better exercises. :: There are only a few exercises in the first edition simply because I have not had time to write more. I have toyed with the =exams= package \cite{exams} and I believe that it is a right way to move forward. As I learn more about what the package can do I would like to incorporate it into later editions of this book.


#+latex: \section*{About This Document}

\IPSUR contains many interrelated parts: the /Document/, the /Program/, the /Package/, and the /Ancillaries/. In short, the /Document/ is what you are reading right now. The /Program/ provides an efficient means to modify the Document. The /Package/ is an \textsf{R} package that houses the Program and the Document. Finally, the /Ancillaries/ are extra materials that reside in the Package and were produced by the Program to supplement use of the Document. We briefly describe each of them in turn.

#+latex: \subsection*{The Document}

The /Document/ is that which you are reading right now -- \IPSUR's /raison d'\^etre/. There are transparent copies (nonproprietary text files) and opaque copies (everything else). See the GNU-FDL in Appendix \ref{cha:GNU-Free-Documentation} for more precise language and details.


- IPSUR.tex :: is a transparent copy of the Document to be typeset with a \LaTeX{} distribution such as Mik\TeX{} or \TeX{} Live. Any reader is free to modify the Document and release the modified version in accordance with the provisions of the GNU-FDL. Note that this file cannot be used to generate a randomized copy of the Document. Indeed, in its released form it is only capable of typesetting the exact version of \IPSUR which you are currently reading. Furthermore, the =.tex= file is unable to generate any of the ancillary materials. 

- IPSUR-xxx.eps, IPSUR-xxx.pdf :: are the image files for every graph in the Document. These are needed when typesetting with \LaTeX{}.

- IPSUR.pdf :: is an opaque copy of the Document. This is the file that instructors would likely want to distribute to students. 

- IPSUR.dvi :: is another opaque copy of the Document in a different file format.

#+latex: \subsection*{The Program}

The /Program/ includes =IPSUR.lyx= and its nephew =IPSUR.Rnw=; the purpose of each is to give individuals a way to quickly customize the Document for their particular purpose(s).


- IPSUR.lyx :: is the source \LyX{} file for the Program, released under the GNU General Public License (GNU GPL) Version 3. This file is opened, modified, and compiled with \LyX{}, a sophisticated open-source document processor, and may be used (together with =Sweave=) to generate a randomized, modified copy of the Document with brand new data sets for some of the exercises and the solution manuals (in the Second Edition). Additionally, \LyX{} can easily activate/deactivate entire blocks of the document, /e.g./~the \textsf{proofs} of the theorems, the student \textsf{solutions} to the exercises, or the instructor \textsf{answers} to the problems, so that the new author may choose which sections (s)he would like to include in the final Document (again, Second Edition). The =IPSUR.lyx= file is all that a person needs (in addition to a properly configured system -- see Appendix \ref{cha:Instructions-for-Instructors}) to generate/compile/export to all of the other formats described above and below, which includes the ancillary materials =IPSUR.Rdata= and =IPSUR.R=.

- IPSUR.Rnw :: is another form of the source code for the Program, also released under the GNU GPL Version 3. It was produced by exporting =IPSUR.lyx= into\textsf{ R}/Sweave format (=.Rnw=). This file may be processed with Sweave to generate a randomized copy of =IPSUR.tex= -- a transparent copy of the Document -- together with the ancillary materials =IPSUR.Rdata= and =IPSUR.R=. Please note, however, that =IPSUR.Rnw= is just a simple text file which does not support many of the extra features that \LyX{} offers such as WYSIWYM editing, instantly (de)activating branches of the manuscript, and more. 



#+latex: \subsection*{The Package}

There is a contributed package on =CRAN=, called =IPSUR=. The package affords many advantages, one being that it houses the  Document in an easy-to-access medium. Indeed, a student can have the Document at his/her fingertips with only three commands:

#+begin_src R :eval never
install.packages("IPSUR")
library(IPSUR)
read(IPSUR)
#+end_src

Another advantage goes hand in hand with the Program's license; since \IPSUR is free, the source code must be freely available to anyone that wants it. A package hosted on =CRAN= allows the author to obey the license by default.

A much more important advantage is that the excellent facilities at \textsf{R}-Forge are building and checking the package daily against patched and development versions of the absolute latest pre-release of \textsf{R}. If any problems surface then I will know about it within 24 hours.

And finally, suppose there is some sort of problem. The package structure makes it /incredibly/ easy for me to distribute bug-fixes and corrected typographical errors. As an author I can make my corrections, upload them to the repository at \textsf{R}-Forge, and they will be reflected /worldwide/ within hours. We aren't in Kansas anymore, Toto.

#+latex: \subsection*{Ancillary Materials}

These are extra materials that accompany \IPSUR. They reside in the =/etc= subdirectory of the package source. 

- IPSUR.RData :: is a saved image of the \textsf{R} workspace at the completion of the Sweave processing of \IPSUR. It can be loaded into memory with \textsf{File} \(\triangleright\) \textsf{Load Workspace} or with the command =load("/path/to/IPSUR.Rdata")=. Either method will make every single object in the file immediately available and in memory. In particular, the data BLANK from Exercise BLANK in Chapter BLANK on page BLANK will be loaded. Type BLANK at the command line (after loading =IPSUR.RData=) to see for yourself.  

- IPSUR.R :: is the exported \textsf{R} code from =IPSUR.Rnw=. With this script, literally every \textsf{R} command from the entirety of \IPSUR can be resubmitted at the command line.

#+latex: \section*{Notation}

We use the notation =x= or =stem.leaf= notation to denote objects, functions, /etc/.. The sequence ``\textsf{Statistics} \textsf{\(\triangleright\)} \textsf{Summaries} \textsf{\(\triangleright\)} \textsf{Active Dataset}'' means to click the \textsf{Statistics} menu item, next click the \textsf{Summaries} submenu item, and finally click \textsf{Active Dataset}.

#+latex: \section*{Acknowledgements}

This book would not have been possible without the firm mathematical and statistical foundation provided by the professors at Bowling Green State University, including Drs. G\'{a}bor Sz\'{e}kely, Craig Zirbel, Arjun K. Gupta, Hanfeng Chen, Truc Nguyen, and James Albert. I would also like to thank Drs.~Neal Carothers and Kit Chan. 

I would also like to thank my colleagues at Youngstown State University for their support. In particular, I would like to thank Dr. G. Andy Chang for showing me what it means to be a statistician.

I would like to thank Richard Heiberger for his insightful comments and improvements to several points and displays in the manuscript. 

Finally, and most importantly, I would like to thank my wife for her patience and understanding while I worked hours, days, months, and years on a /free book/. Looking back, I can't believe I ever got away with it.

#+begin_latex
\vfill{}
\cleardoublepage
\phantomsection
\addcontentsline{toc}{chapter}{List of Figures}
\listoffigures

\vfill{}
\cleardoublepage
\phantomsection
\addcontentsline{toc}{chapter}{List of Tables}
\listoftables
#+end_latex
