#+STARTUP: indent
#+TITLE:     Sampling Distributions
#+AUTHOR:    G. Jay Kerns
#+EMAIL:     gkerns@ysu.edu
#+DATE:      2011-09-18 Sun
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:


* Sampling Distributions
\label{cha:Sampling-Distributions}

\noindent This is an important chapter; it is the bridge from probability and descriptive statistics that we studied in Chapters \ref{cha:Describing-Data-Distributions} through \ref{cha:Multivariable-Distributions} to inferential statistics which forms the latter part of this book.

Here is the link: we are presented with a /population/ about which we would like to learn. And while it would be desirable to examine every single member of the population, we find that it is either impossible or infeasible to for us to do so, thus, we resort to collecting a /sample/ instead. We do not lose heart. Our method will suffice, provided the sample is /representative/ of the population. A good way to achieve this is to sample /randomly/ from the population.

Supposing for the sake of argument that we have collected a random sample, the next task is to make some /sense/ out of the data because the complete list of sample information is usually cumbersome, unwieldy. We summarize the data set with a descriptive /statistic/, a quantity calculated from the data (we saw many examples of these in Chapter \ref{cha:Describing-Data-Distributions}). But our sample was random... therefore, it stands to reason that our statistic will be random, too. How is the statistic distributed?

The probability distribution associated with the population (from which we sample) is called the /population distribution/, and the probability distribution associated with our statistic is called its /sampling distribution/; clearly, the two are interrelated. To learn about the population distribution, it is imperative to know everything we can about the sampling distribution. Such is the goal of this chapter.

We begin by introducing the notion of simple random samples and cataloguing some of their more convenient mathematical properties. Next we focus on what happens in the special case of sampling from the normal distribution (which, again, has several convenient mathematical properties), and in particular, we meet the sampling distribution of \(\overline{X}\) and \(S^{2}\). Then we explore what happens to \(\overline{X}\)'s sampling distribution when the population is not normal and prove one of the most remarkable theorems in statistics, the Central Limit Theorem (CLT).

With the CLT in hand, we then investigate the sampling distributions of several other popular statistics, taking full advantage of those with a tractable form. We finish the chapter with an exploration of statistics whose sampling distributions are not quite so tractable, and to accomplish this goal we will use simulation methods that are grounded in all of our work in the previous four chapters.

#+latex: \paragraph*{What do I want them to know?}

- the notion of population versus simple random sample, parameter versus statistic, and population distribution versus sampling distribution
- the classical sampling distributions of the standard one and two sample statistics
- how to generate a simulated sampling distribution when the statistic is crazy
- the Central Limit Theorem, period.
- some basic concepts related to sampling distribution utility, such as bias and variance

** Simple Random Samples
\label{sec:simple-random-samples}

*** Simple Random Samples
\label{sub:simple-random-samples}

#+latex: \begin{defn}
If \(X_{1}\), \(X_{2}\), ..., \(X_{n}\) are independent with \(X_{i}\sim f\) for \(i=1,2,\ldots,n\), then we say that \(X_{1}\), \(X_{2}\), ..., \(X_{n}\) are /independent and identically distributed/ (IID) from the population \(f\) or alternatively we say that \(X_{1}\), \(X_{2}\), ..., \(X_{n}\) are a /simple random sample of size/ \(n\), denoted \(SRS(n)\), from the population \(f\). 
#+latex: \end{defn}

#+latex: \begin{prop}
\label{pro:mean-sd-xbar}
Let \(X_{1}\), \(X_{2}\), ..., \(X_{n}\) be a \(SRS(n)\) from a population distribution with mean \(\mu\) and finite standard deviation \(\sigma\). Then the mean and standard deviation of \(\overline{X}\) are given by the formulas \(\mu_{\overline{X}}=\mu\) and \(\sigma_{\overline{X}}=\sigma/\sqrt{n}\).
#+latex: \end{prop}

#+latex: \begin{proof}
Plug in \(a_{1}=a_{2}=\cdots=a_{n}=1/n\) in Proposition \ref{pro:mean-sd-lin-comb}.
#+latex: \end{proof}

The next fact will be useful to us when it comes time to prove the Central Limit Theorem in Section \ref{sec:Central-Limit-Theorem}.

#+latex: \begin{prop}
\label{pro:mgf-xbar}
Let \(X_{1}\), \(X_{2}\), ..., \(X_{n}\) be a \(SRS(n)\) from a population distribution with MGF \(M(t)\). Then the MGF of \(\overline{X}\) is given by
\begin{equation}
M_{\overline{X}}(t)=\left[M\left(\frac{t}{n}\right)\right]^{n}.
\end{equation}
#+latex: \end{prop}

#+latex: \begin{proof}
Go from the definition:
\begin{eqnarray*}
M_{\overline{X}}(t) & = & \E\,\mathrm{e}^{t\overline{X}},\\
 & = & \E\,\mathrm{e}^{t(X_{1}+\cdots+X_{n})/n},\\
 & = & \E\,\mathrm{e}^{tX_{1}/n}\mathrm{e}^{tX_{2}/n}\cdots\mathrm{e}^{tX_{n}/n}.
\end{eqnarray*}
And because \(X_{1}\), \(X_{2}\), ..., \(X_{n}\) are independent, Proposition \ref{pro:indep-implies-prodexpect} allows us to distribute the expectation among each term in the product, which is
\[
\E\mathrm{e}^{tX_{1}/n}\,\E\mathrm{e}^{tX_{2}/n}\cdots\E\mathrm{e}^{tX_{n}/n}.
\]
The last step is to recognize that each term in last product above is exactly \(M(t/n)\).
#+latex: \end{proof}

** Sampling from a Normal Distribution
\label{sec:sampling-from-normal-dist}

*** The Distribution of the Sample Mean
\label{sub:samp-mean-dist-of}

#+latex: \begin{prop}
Let \(X_{1}\), \(X_{2}\), ..., \(X_{n}\) be a \(SRS(n)\) from a \(\mathsf{norm}(\mathtt{mean}=\mu,\,\mathtt{sd}=\sigma)\) distribution. Then the sample mean \(\overline{X}\) has a \(\mathsf{norm}(\mathtt{mean}=\mu,\,\mathtt{sd}=\sigma/\sqrt{n})\) sampling distribution.
#+latex: \end{prop}

#+latex: \begin{proof}
The mean and standard deviation of \(\overline{X}\) follow directly from Proposition \ref{pro:mean-sd-xbar}. To address the shape, first remember from Section \ref{sec:The-Normal-Distribution} that the \(\mathsf{norm}(\mathtt{mean}=\mu,\,\mathtt{sd}=\sigma)\) MGF is of the form
\[
M(t)=\exp\left[ \mu t+\sigma^{2}t^{2}/2\right] .
\]
Now use Proposition \ref{pro:mgf-xbar} to find
\begin{eqnarray*}
M_{\overline{X}}(t) & = & \left[M\left(\frac{t}{n}\right)\right]^{n},\\
 & = & \left[\exp\left( \mu(t/n)+\sigma^{2}(t/n)^{2}/2\right) \right]^{n},\\
 & = & \exp\left( \, n\cdot\left[\mu(t/n)+\sigma^{2}(t/n)^{2}/2\right]\right) ,\\
 & = & \exp\left( \mu t+(\sigma/\sqrt{n})^{2}t^{2}/2\right),
\end{eqnarray*}
and we recognize this last quantity as the MGF of a \(\mathsf{norm}(\mathtt{mean}=\mu,\,\mathtt{sd}=\sigma/\sqrt{n})\) distribution.
#+latex: \end{proof}

*** The Distribution of the Sample Variance
\label{sub:Samp-Var-Dist}

#+latex: \begin{thm}
\label{thm:Xbar-andS}
Let \(X_{1}\), \(X_{2}\), ..., \(X_{n}\) be a \(SRS(n)\) from a \(\mathsf{norm}(\mathtt{mean}=\mu,\,\mathtt{sd}=\sigma)\) distribution, and let
\begin{equation}
\overline{X}=\sum_{i=1}^{n}X_{i}\quad\mbox{and}\quad S^{2}=\frac{1}{n-1}\sum_{i=1}^{n}(X_{i}-\overline{X})^{2}.
\end{equation}
Then
1. \(\overline{X}\) and \(S^{2}\) are independent, and
2. The rescaled sample variance
    \begin{equation}
    \frac{(n-1)}{\sigma^{2}}S^{2}=\frac{\sum_{i=1}^{n}(X_{i}-\overline{X})^{2}}{\sigma^{2}}
    \end{equation}
    has a \(\mathsf{chisq}(\mathtt{df}=n-1)\) sampling distribution.
#+latex: \end{thm}

#+latex: \begin{proof}
The proof is beyond the scope of the present book, but the theorem is simply too important to be omitted. The interested reader could consult Casella and Berger \cite{Casella2002}, or Hogg /et al/ \cite{Hogg2005}. 
#+latex: \end{proof}

*** The Distribution of Student's \(T\) Statistic
\label{sub:Student's-t-Distribution}

#+latex: \begin{prop}
Let \(X_{1}\), \(X_{2}\), ..., \(X_{n}\) be a \(SRS(n)\) from a \(\mathsf{norm}(\mathtt{mean}=\mu,\,\mathtt{sd}=\sigma)\) distribution. Then the quantity 
\begin{equation}
T=\frac{\overline{X}-\mu}{S/\sqrt{n}}
\end{equation}
has a \(\mathsf{t}(\mathtt{df}=n-1)\) sampling distribution.
#+latex: \end{prop}

#+latex: \begin{proof}
Divide the numerator and denominator by \(\sigma\) and rewrite
\[
T=\frac{\frac{\overline{X}-\mu}{\sigma/\sqrt{n}}}{S/\sigma}=\frac{\frac{\overline{X}-\mu}{\sigma/\sqrt{n}}}{\sqrt{\left.\frac{(n-1)S^{2}}{\sigma^{2}}\right\slash (n-1)}}.
\]
Now let 
\[
Z=\frac{\overline{X}-\mu}{\sigma/\sqrt{n}}\quad\mbox{and}\quad V=\frac{(n-1)S^{2}}{\sigma^{2}},
\]
so that
\begin{equation}
T=\frac{Z}{\sqrt{V/r}},
\end{equation}
where \(r=n-1\).

We know from Section \ref{sub:samp-mean-dist-of} that \(Z\sim\mathsf{norm}(\mathtt{mean}=0,\,\mathtt{sd}=1)\) and we know from Section \ref{sub:Samp-Var-Dist} that \(V\sim\mathsf{chisq}(\mathtt{df}=n-1)\). Further, since we are sampling from a normal distribution, Theorem \ref{thm:Xbar-andS} gives that \(\overline{X}\) and \(S^{2}\) are independent and by Fact \ref{fac:indep-then-function-indep} so are \(Z\) and \(V\). In summary, the distribution of \(T\) is the same as the distribution of the quantity \(Z/\sqrt{V/r}\), where \(Z\sim\mathsf{norm}(\mathtt{mean}=0,\,\mathtt{sd}=1)\) and \(V\sim\mathsf{chisq}(\mathtt{df}=r)\) are independent. This is in fact the definition of Student's \(t\) distribution.
#+latex: \end{proof}

This distribution was first published by W. S. Gosset (1900) under the pseudonym Student, and the distribution has consequently come to be known as Student's \(t\) distribution. The PDF of \(T\) can be derived explicitly using the techniques of Section \ref{sec:Functions-of-Continuous}; it takes the form 
\begin{equation}
f_{X}(x)=\frac{\Gamma[(r+1)/2]}{\sqrt{r\pi}\ \Gamma(r/2)}\left(1+\frac{x^{2}}{r}\right)^{-(r+1)/2},\quad-\infty<x<\infty.
\end{equation}
Any random variable \(X\) with the preceding PDF is said to have Student's \(t\) distribution with \(r\) /degrees of freedom/, and we write \(X\sim\mathsf{t}(\mathtt{df}=r)\). The shape of the PDF is similar to the normal, but the tails are considerably heavier. See Figure \ref{fig:Student's-t-dist-vary-df}. As with the normal distribution, there are four functions in \textsf{R} associated with the \(t\) distribution, namely =dt=, =pt=,=qt=, and =rt=, which compute the PDF, CDF, quantile function, and generate random variates, respectively.


The code to produce Figure \ref{fig:Student's-t-dist-vary-df} is
#+begin_src R :exports code :results graphics silent :file img/Student's-t-dist-vary-df.pdf
curve(dt(x, df = 30), from = -3, to = 3, lwd = 3, ylab = "y")
ind <- c(1, 2, 3, 5, 10)
for (i in ind) curve(dt(x, df = i), -3, 3, add = TRUE)
#+end_src

#+begin_src latex 
  \begin{figure}[th]
    \includegraphics[width=5in, height=4in]{img/Student's-t-dist-vary-df.pdf}
    \caption[Student's \(t\) distribution for various degrees of freedom]{\small A plot of Student's \(t\) distribution for various degrees of freedom.}
    \label{fig:Student's-t-dist-vary-df}
  \end{figure}
#+end_src

Similar to that done for the normal we may define \(\mathsf{t}_{\alpha}(\mathtt{df}=n-1)\) as the number on the \(x\)-axis such that there is exactly \(\alpha\) area under the \(\mathsf{t}(\mathtt{df}=n-1)\) curve to its right.

#+latex: \begin{example}
Find \(\mathsf{t}{}_{0.01}(\mathtt{df}=23)\) with the quantile function.
#+latex: \end{example}

#+begin_src R :exports both :results output pp 
qt(0.01, df = 23, lower.tail = FALSE)
#+end_src

#+latex: \begin{rem}
There are a few things to note about the \(\mathtt{t}(\mathtt{df}=r)\) distribution.
1. The \(\mathtt{t}(\mathtt{df}=1)\) distribution is the same as the \(\mathsf{cauchy}(\mathtt{location}=0,\,\mathtt{scale}=1)\) distribution. The Cauchy distribution is rather pathological and is a counterexample to many famous results. 
2. The standard deviation of \(\mathsf{t}(\mathtt{df}=r)\) is undefined (that is, infinite) unless \(r>2\). When \(r\) is more than 2, the standard deviation is always bigger than one, but decreases to 1 as \(r\to\infty\).
3. As \(r\to\infty\), the \(\mathtt{t}(\mathtt{df}=r)\) distribution approaches the \(\mathsf{norm}(\mathtt{mean}=0,\,\mathtt{sd}=1)\) distribution.
#+latex: \end{rem}

** The Central Limit Theorem
\label{sec:Central-Limit-Theorem}

In this section we study the distribution of the sample mean when the underlying distribution is /not/ normal. We saw in Section \ref{sec:sampling-from-normal-dist} that when \(X_{1}\), \(X_{2}\), ... , \(X_{n}\) is a \(SRS(n)\) from a \(\mathsf{norm}(\mathtt{mean}=\mu,\,\mathtt{sd}=\sigma)\) distribution then \(\overline{X}\sim\mathsf{norm}(\mathtt{mean}=\mu,\,\mathtt{sd}=\sigma/\sqrt{n})\). In other words, we may say (owing to Fact \ref{fac:lin-trans-norm-is-norm}) when the underlying population is normal that the sampling distribution of \(Z\) defined by
\begin{equation}
Z=\frac{\overline{X}-\mu}{\sigma/\sqrt{n}}
\end{equation}
is \(\mathsf{norm}(\mathtt{mean}=0,\,\mathtt{sd}=1)\). 

However, there are many populations that are /not/ normal ... and the statistician often finds herself sampling from such populations. What can be said in this case? The surprising answer is contained in the following theorem.

#+latex: \begin{thm}
\label{thm:central-limit-thrm}
*The Central Limit Theorem.* Let \(X_{1}\), \(X_{2}\), ..., \(X_{n}\) be a \(SRS(n)\) from a population distribution with mean \(\mu\) and finite standard deviation \(\sigma\). Then the sampling distribution of 
\begin{equation}
Z=\frac{\overline{X}-\mu}{\sigma/\sqrt{n}}
\end{equation}
approaches a \(\mathsf{norm}(\mathtt{mean}=0,\,\mathtt{sd}=1)\) distribution as \(n\to\infty\).
#+latex: \end{thm}

#+latex: \begin{rem}
We suppose that \(X_{1}\), \(X_{2}\), ... , \(X_{n}\) are IID, and we learned in Section \ref{sub:simple-random-samples} that \(\overline{X}\) has mean \(\mu\) and standard deviation \(\sigma/\sqrt{n}\), so we already knew that \(Z\) has mean zero and standard deviation one. The beauty of the CLT is that it addresses the /shape/ of \(Z\)'s distribution when the sample size is large.
#+latex: \end{rem}

#+latex: \begin{rem}
Notice that the shape of the underlying population's distribution is not mentioned in Theorem \ref{thm:central-limit-thrm}; indeed, the result is true for any population that is well-behaved enough to have a finite standard deviation. In particular, if the population is normally distributed then we know from Section \ref{sub:samp-mean-dist-of} that the distribution of \(\overline{X}\) (and \(Z\) by extension) is /exactly/ normal, for /every/ \(n\).
#+latex: \end{rem}

#+latex: \begin{rem}
How large is ``sufficiently large''? It is here that the shape of the underlying population distribution plays a role. For populations with distributions that are approximately symmetric and mound-shaped, the samples may need to be only of size four or five, while for highly skewed or heavy-tailed populations the samples may need to be much larger for the distribution of the sample means to begin to show a bell-shape. Regardless, for a given population distribution (with finite standard deviation) the approximation tends to be better for larger sample sizes.
#+latex: \end{rem}

#+latex: \paragraph*{How to do it with \textsf{R}}

The =TeachingDemos= package \cite{Snowteachingdemos} has =clt.examp= and the =distrTeach= \cite{Ruckdescheldistr} package has =illustrateCLT=. Try the following at the command line (output omitted):
#+begin_src R :exports code :eval never
library(TeachingDemos)
example(clt.examp)
#+end_src
and
#+begin_src R :exports code :eval never
library(distrTeach)
example(illustrateCLT)
#+end_src

The =IPSUR=  package has the functions =clt1=, =clt2=, and =clt3= (see Exercise \ref{xca:clt123} at the end of this chapter). Its purpose is to investigate what happens to the sampling distribution of \(\overline{X}\) when the population distribution is mound shaped, finite support, and skewed, namely \(\mathsf{t}(\mathtt{df}=3)\), \(\mathsf{unif}(\mathtt{a}=0,\,\mathtt{b}=10)\), and \(\mathsf{gamma}(\mathtt{shape}=1.21,\,\mathtt{scale}=1/2.37)\), respectively. 

For example, when the command =clt1()=  is issued a plot window opens to show a graph of the PDF of a \(\mathsf{t}(\mathtt{df}=3)\) distribution. On the display are shown numerical values of the population mean and variance. While the students examine the graph the computer is simulating random samples of size =sample.size = 2= from the population distribution =rt= a total of =N.iter = 100000= times, and sample means are calculated of each sample. Next follows a histogram of the simulated sample means, which closely approximates the sampling distribution of \(\overline{X}\), see Section \ref{sec:Simulated-Sampling-Distributions}. Also shown are the sample mean and sample variance of all of the simulated  \( \overline{X} \) values. As a final step, when the student clicks the second plot, a normal curve with the same mean and variance as the simulated \( \overline{X} \) values is superimposed over the histogram. Students should compare the population theoretical mean and variance to the simulated mean and variance of the sampling distribution. They should also compare the shape of the simulated sampling distribution to the shape of the normal distribution.

The three separate =clt1=, =clt2=, and =clt3= functions were written so that students could compare what happens overall when the shape of the population distribution changes. It would be possible to combine all three into one big function, =clt= which covers all three cases (and more). 

** Sampling Distributions of Two-Sample Statistics
\label{sec:Samp-Dist-Two-Samp}

There are often two populations under consideration, and it sometimes of interest to compare properties between groups. To do so we take independent samples from each population and calculate respective sample statistics for comparison. In some simple cases the sampling distribution of the comparison is known and easy to derive; such cases are the subject of the present section.

*** Difference of Independent Sample Means

#+latex: \begin{prop}
Let \(X_{1}\), \(X_{2}\), ... , \(X_{n_{1}}\) be an \(SRS(n_{1})\) from a \(\mathsf{norm}(\mathtt{mean}=\mu_{X},\,\mathtt{sd}=\sigma_{X})\) distribution and let \(Y_{1}\), \(Y_{2}\), ... , \(Y_{n_{2}}\) be an \(SRS(n_{2})\) from a \(\mathsf{norm}(\mathtt{mean}=\mu_{Y},\,\mathtt{sd}=\sigma_{Y})\) distribution. Suppose that \(X_{1}\), \(X_{2}\), ... , \(X_{n_{1}}\) and \(Y_{1}\), \(Y_{2}\), ... , \(Y_{n_{2}}\) are independent samples. Then the quantity
\begin{equation}
\frac{\overline{X}-\overline{Y}-(\mu_{X}-\mu_{Y})}{\sqrt{\left.\sigma_{X}^{2}\right\slash n_{1}+\left.\sigma_{Y}^{2}\right\slash n_{2}}}\label{eq:diff-indep-sample-means}\end{equation}
has a \(\mathsf{norm}(\mathtt{mean}=0,\,\mathtt{sd}=1)\) sampling distribution. Equivalently, \(\overline{X}-\overline{Y}\) has a \(\mathsf{norm}(\mathtt{mean}=\mu_{X}-\mu_{Y},\,\mathtt{sd}=\sqrt{\left.\sigma_{X}^{2}\right\slash n_{1}+\left.\sigma_{Y}^{2}\right\slash n_{2}})\) sampling distribution.
#+latex: \end{prop}

#+latex: \begin{proof}
We know that \(\overline{X}\) is \(\mathsf{norm}(\mathtt{mean}=\mu_{X},\,\mathtt{sd}=\sigma_{X}/\sqrt{n_{1}})\) and we also know that \(\overline{Y}\) is \(\mathsf{norm}(\mathtt{mean}=\mu_{Y},\,\mathtt{sd}=\sigma_{Y}/\sqrt{n_{2}})\). And since the samples \(X_{1}\), \(X_{2}\), ..., \(X_{n_{1}}\) and \(Y_{1}\), \(Y_{2}\), ..., \(Y_{n_{2}}\) are independent, so too are \(\overline{X}\) and \(\overline{Y}\). The distribution of their difference is thus normal as well, and the mean and standard deviation are given by Proposition \ref{pro:mean-sd-lin-comb-two}.
#+latex: \end{proof}

#+latex: \begin{rem}
Even if the distribution of one or both of the samples is not normal, the quantity in Equation \ref{eq:diff-indep-sample-means} will be approximately normal provided both sample sizes are large.
#+latex: \end{rem}

#+latex: \begin{rem}
For the special case of \(\mu_{X}=\mu_{Y}\) we have shown that 
\begin{equation} \frac{\overline{X}-\overline{Y}}{\sqrt{\sigma_{X}^{2}/n_{1}+\sigma_{Y}^{2}/n_{2}}}
\end{equation}
has a \(\mathsf{norm}(\mathtt{mean}=0,\,\mathtt{sd}=1)\) sampling distribution, or in other words, \(\overline{X}-\overline{Y}\) has a \(\mathsf{norm}(\mathtt{mean}=0,\,\mathtt{sd}=\sqrt{\sigma_{X}^{2}/n_{1}+\sigma_{Y}^{2}/n_{2}})\) sampling distribution. This will be important when it comes time to do hypothesis tests; see Section \ref{sec:Conf-Interv-for-Diff-Means}.
#+latex: \end{rem}


*** Difference of Independent Sample Proportions

#+latex: \begin{prop}
Let \(X_{1}\), \(X_{2}\), ..., \(X_{n_{1}}\) be an \(SRS(n_{1})\) from a \(\mathsf{binom}(\mathtt{size}=1,\,\mathtt{prob}=p_{1})\) distribution and let \(Y_{1}\), \(Y_{2}\), ..., \(Y_{n_{2}}\) be an \(SRS(n_{2})\) from a \(\mathsf{binom}(\mathtt{size}=1,\,\mathtt{prob}=p_{2})\) distribution. Suppose that \(X_{1}\), \(X_{2}\), ... , \(X_{n_{1}}\) and \(Y_{1}\), \(Y_{2}\), ... , \(Y_{n_{2}}\) are independent samples. Define 
\begin{equation}
\hat{p}_{1}=\frac{1}{n_{1}}\sum_{i=1}^{n_{1}}X_{i}\quad\mbox{and}\quad\hat{p}_{2}=\frac{1}{n_{2}}\sum_{j=1}^{n_{2}}Y_{j}.
\end{equation}
Then the sampling distribution of
\begin{equation}
\frac{\hat{p}_{1}-\hat{p}_{2}-(p_{1}-p_{2})}{\sqrt{\frac{p_{1}(1-p_{1})}{n_{1}}+\frac{p_{2}(1-p_{2})}{n_{2}}}}
\end{equation}
approaches a \(\mathsf{norm}(\mathtt{mean}=0,\,\mathtt{sd}=1)\) distribution as both \(n_{1},\, n_{2}\to\infty\). In other words, the sampling distribution of \(\hat{p}_{1}-\hat{p}_{2}\) is approximately
\begin{equation}
\mathsf{norm}\left(\mathtt{mean}=p_{1}-p_{2},\,\mathtt{sd}=\sqrt{\frac{p_{1}(1-p_{1})}{n_{1}}+\frac{p_{2}(1-p_{2})}{n_{2}}}\right),
\end{equation}
provided both \(n_{1}\) and \(n_{2}\) are sufficiently large.
#+latex: \end{prop}

#+latex: \begin{proof}
We know that \(\hat{p}_{1}\) is approximately normal for \(n_{1}\) sufficiently large by the CLT, and we know that \(\hat{p}_{2}\) is approximately normal for \(n_{2}\) sufficiently large, also by the CLT. Further, \(\hat{p}_{1}\) and \(\hat{p}_{2}\) are independent since they are derived from independent samples. And a difference of independent (approximately) normal distributions is (approximately) normal, by Exercise \ref{xca:diff-indep-norm}.
#+latex: \footnote{This does not explicitly follow because of our cavalier use of ``approximately'' in too many places. To be more thorough, however, would require more concepts than we can afford at the moment. The interested reader may consult a more advanced text, specifically the topic of weak convergence, that is, convergence in distribution.}
The expressions for the mean and standard deviation follow immediately from Proposition \ref{pro:mean-sd-lin-comb-two} combined with the formulas for the \(\mathsf{binom}(\mathtt{size}=1,\,\mathtt{prob}=p)\) distribution from Chapter \ref{cha:Discrete-Distributions}.
#+latex: \end{proof}

*** Ratio of Independent Sample Variances

#+latex: \begin{prop}
Let \(X_{1}\), \(X_{2}\), ..., \(X_{n_{1}}\) be an \(SRS(n_{1})\) from a \(\mathsf{norm}(\mathtt{mean}=\mu_{X},\,\mathtt{sd}=\sigma_{X})\) distribution and let \(Y_{1}\), \(Y_{2}\), ... , \(Y_{n_{2}}\) be an \(SRS(n_{2})\) from a \(\mathsf{norm}(\mathtt{mean}=\mu_{Y},\,\mathtt{sd}=\sigma_{Y})\) distribution. Suppose that \(X_{1}\), \(X_{2}\), ... , \(X_{n_{1}}\) and \(Y_{1}\), \(Y_{2}\), ... , \(Y_{n_{2}}\) are independent samples. Then the ratio
\begin{equation}
F=\frac{\sigma_{Y}^{2}S_{X}^{2}}{\sigma_{X}^{2}S_{Y}^{2}}
\end{equation}
has an \(\mathsf{f}(\mathtt{df1}=n_{1}-1,\,\mathtt{df2}=n_{2}-1)\) sampling distribution.
#+latex: \end{prop}

#+latex: \begin{proof}
We know from Theorem \ref{thm:Xbar-andS} that \((n_{1}-1)S_{X}^{2}/\sigma_{X}^{2}\) is distributed \(\mathsf{chisq}(\mathtt{df}=n_{1}-1)\) and \((n_{2}-1)S_{Y}^{2}/\sigma_{Y}^{2}\) is distributed \(\mathsf{chisq}(\mathtt{df}=n_{2}-1)\). Now write
\[
F=\frac{\sigma_{Y}^{2}S_{X}^{2}}{\sigma_{X}^{2}S_{Y}^{2}}=\frac{\left.(n_{1}-1)S_{Y}^{2}\right\slash (n_{1}-1)}{\left.(n_{2}-1)S_{Y}^{2}\right\slash (n_{2}-1)}\cdot\frac{\left.1\right\slash \sigma_{X}^{2}}{\left.1\right\slash \sigma_{Y}^{2}},
\]
by multiplying and dividing the numerator with \(n_{1}-1\) and doing likewise for the denominator with \(n_{2}-1\). Now we may regroup the terms into
\[
F=\frac{\left.\frac{(n_{1}-1)S_{X}^{2}}{\sigma_{X}^{2}}\right\slash (n_{1}-1)}{\left.\frac{(n_{2}-1)S_{Y}^{2}}{\sigma_{Y}^{2}}\right\slash (n_{2}-1)},
\]
and we recognize \(F\) to be the ratio of independent \(\mathsf{chisq}\) distributions, each divided by its respective numerator \(\mathtt{df}=n_{1}-1\) and denominator \(\mathtt{df}=n_{1}-1\) degrees of freedom. This is, indeed, the definition of Snedecor's \(F\) distribution. 
#+latex: \end{proof}

#+latex: \begin{rem}
For the special case of \(\sigma_{X}=\sigma_{Y}\) we have shown that
\begin{equation}
F=\frac{S_{X}^{2}}{S_{Y}^{2}}
\end{equation}
has an \(\mathsf{f}(\mathtt{df1}=n_{1}-1,\,\mathtt{df2}=n_{2}-1)\) sampling distribution. This will be important in Chapters \ref{cha:Estimation} onward.
#+latex: \end{rem}

** Simulated Sampling Distributions
\label{sec:Simulated-Sampling-Distributions}

Some comparisons are meaningful, but their sampling distribution is not quite so tidy to describe analytically. What do we do then?

As it turns out, we do not need to know the exact analytical form of the sampling distribution; sometimes it is enough to approximate it with a simulated distribution. In this section we will show you how. Note that \textsf{R} is particularly well suited to compute simulated sampling distributions, much more so than, say, SPSS or SAS.

*** The Interquartile Range

#+begin_src R :exports code :results silent 
iqrs <- replicate(100, IQR(rnorm(100)))
#+end_src

We can look at the mean of the simulated values
#+begin_src R :exports both :results output pp 
mean(iqrs)    # close to 1
#+end_src

and we can see the standard deviation
#+begin_src R :exports both :results output pp 
sd(iqrs)
#+end_src

Now let's take a look at a plot of the simulated values

#+begin_src R :exports code :results graphics silent :file img/simulated-IQR.pdf
hist(iqrs, breaks = 20)
#+end_src

#+begin_src latex 
  \begin{figure}[th]
    \includegraphics[width=5in, height=4in]{img/simulated-IQR.pdf}
    \caption[Plot of simulated IQRs]{\small A plot of simulated IQRs.}
    \label{fig:simulated-IQR}
  \end{figure}
#+end_src

*** The Median Absolute Deviation

#+begin_src R :exports code :results silent
mads <- replicate(100, mad(rnorm(100)))
#+end_src

We can look at the mean of the simulated values

#+begin_src R :exports both :results output pp 
mean(mads)    # close to 1.349
#+end_src

and we can see the standard deviation

#+begin_src R :exports both :results output pp 
sd(mads)
#+end_src

Now let's take a look at a plot of the simulated values

#+begin_src R :exports code :results graphics silent :file img/simulated-MAD.pdf
hist(mads, breaks = 20)
#+end_src

#+begin_src latex 
  \begin{figure}[th]
    \includegraphics[width=5in, height=4in]{img/simulated-MAD.pdf}
    \caption[Plot of simulated MADs]{\small A plot of simulated MADs.}
    \label{fig:simulated-MAD}
  \end{figure}
#+end_src

#+latex: \newpage{}

** Exercises
#+latex: \setcounter{thm}{0}

#+begin_src R :exports none :results silent
k <- 1
n <- sample(10:30, size=10, replace = TRUE)
mu <- round(rnorm(10, mean = 20))
#+end_src

#+latex: \begin{xca}
Suppose that we observe a random sample \(X_{1}\), \(X_{2}\), ... , \(X_{n}\) of size \( SRS( n =  SRC_R{n[k]} ) \) from a \( \mathsf{norm}(\mathtt{mean}= SRC_R{mu[k]}) \) distribution. 
1. What is the mean of \(\overline{X}\)?
1. What is the standard deviation of \(\overline{X}\)?
1. What is the distribution of \(\overline{X}\)? (approximately)
1. Find \(\P(a< \overline{X} \leq b)\)
1. Find \(\P(\overline{X} > c)\).
#+latex: \end{xca}

#+latex: \begin{xca}
\label{xca:clt123}
In this exercise we will investigate how the shape of the population distribution affects the time until the distribution of \(\overline{X}\) is acceptably normal.
#+latex: \end{xca}

#+latex: \begin{xca}
Let \(X_{1}\),..., \(X_{25}\) be a random sample from a \(\mathsf{norm}(\mathtt{mean}=37,\,\mathtt{sd}=45)\) distribution, and let \(\overline{X}\) be the sample mean of these \(n=25\) observations.
1. How is \(\overline{X}\) distributed? 
   \(\mathsf{norm}(\mathtt{mean}=37,\,\mathtt{sd}=45/\sqrt{25})\) 
1. Find \(\P(\overline{X} > 43.1)\).
And that's all she wrote.
#+latex: \end{xca}






