#+TITLE:     IPSUR - Feedback
#+AUTHOR:    G. Jay Kerns, Youngstown State University
#+EMAIL:     gkerns@ysu.edu
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:nil LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc email:t
#+INCLUDE: "header/header.org"

* Giving Feedback

I would be happy to hear any (most?) comments, suggestions, problems,
questions, or requests that you may have about =IPSUR=. And if you
would like to ask/say something, then feel free to contact me at
[[mailto:gkerns@ysu.edu][gkerns@ysu.edu]] ([[http://people.ysu.edu/~gkerns/][home page]]).

For the First Edition I set up a couple of mailing lists on R-Forge,
but almost everybody simply wrote me directly. Now that IPSUR has
migrated to Savannah I set up some mailing lists [[http://savannah.nongnu.org/mail/?group=ipsur][here]].

A few people submitted some [[https://github.com/gjkerns/IPSUR/issues][issues and pull requests on GitHub]] which
was pretty cool.  I think that is the only thing I really miss about
GitHub.

If you find a mistake in the narrative, if you have a suggestion
regarding the subject matter, or if you have /constructive/ criticism
of the book, then please let me know. Before writing please bear in
mind that regarding subjective matters I do pledge to amicably listen
to - but I do not promise to agree with - everybody about everything.
Moreover, the fact that =IPSUR= is FREE means that if you don't like
something then you are FREE to rewrite it yourself.  All that being
said I would be delighted to hear about your experiences with the
book, good or bad, in the classroom or elsewhere.

---------------------------------------------------
