#    IPSUR: Introduction to Probability and Statistics Using R
#    Copyright (C) 2014 G. Jay Kerns
#
#    This file is part of IPSUR.
#
#    IPSUR is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    IPSUR is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with IPSUR.  If not, see <http://www.gnu.org/licenses/>.

#+TITLE:     IPSUR: Introduction to Probability and Statistics Using R
#+AUTHOR:    G. Jay Kerns, Youngstown State University
#+EMAIL:     gkerns@ysu.edu
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc email:t
#+INCLUDE:   header/header.org org

*Introduction to Probability and Statistics Using R*, ISBN:
978-0-557-24979-4, is a textbook written for an undergraduate course
in probability and statistics.

IPSUR is [[http://www.gnu.org/copyleft/fdl.html][FREE]], in the [[http://www.gnu.org/][GNU]] sense of the word.

Refer to the [[file:install.org][Install]] page for instructions to install an electronic
copy of =IPSUR= on your personal computer. Check out the [[file:resources.org][Resources]]
page for extra materials that go along with the book.  See the
[[file:feedback.org][Feedback]] page for guidance about questions or comments you may have
about =IPSUR=.

* Downloads

The [[https://savannah.nongnu.org/git/?group=ipsur][Savannah project]] has a [[http://download.savannah.gnu.org/releases/ipsur/][download]] area of currently released files.
Clone the entire Savannah revision history via [[https://en.wikipedia.org/wiki/Git_(software)][Git]] with:

#+BEGIN_SRC sh :eval no-export
$ git clone git://git.savannah.nongnu.org/ipsur.git
#+END_SRC

See also the [[http://r-forge.r-project.org/R/?group_id=58][IPSUR Development Page on R-Forge]]. There still exists an
[[https://github.com/gjkerns/IPSUR][IPSUR page on GitHub]], though development is primarily on Savannah
these days.  Go [[http://git.savannah.gnu.org/cgit/ipsur.git][here]] to browse the recent commit history.

----------------------------------------------------
#+HTML: <font size="2">Bitcoin Donations: <a rel="payment" href="bitcoin:1ADgZaSQ62hcjRteXjoubiUtSZZZd8kn51">1ADgZaSQ62hcjRteXjoubiUtSZZZd8kn51</a></font><br />
-------------------------------------------------
