#+TITLE:     IPSUR - Installation
#+AUTHOR:    G. Jay Kerns, Youngstown State University
#+EMAIL:     gkerns@ysu.edu
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:nil LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc email:t
#+INCLUDE: "header/header.org"

* Installation Instructions

The Second Edition of =IPSUR= has grown to be more like an ordinary
book than the First Edition was, but the =IPSUR= package still exists
and is still supported.  Do the following to get up and running with
the =IPSUR= package.

** Download the latest version of =R=
Choose a link below to download the latest version of =R= for your
operating system from =CRAN=:
#+BEGIN_CENTER
=Windows= - [[http://cran.r-project.org/bin/windows/base/]] \\
=MacOS X= - [[http://cran.r-project.org/bin/macosx/]] \\
=Linux= - [[http://cran.r-project.org/bin/linux/]] 
#+END_CENTER
- *Windows Installation Tip:* click the =.exe= program file to start
  installation.  When it asks for "Customized startup options",
  specify /Yes/.  In the next window, be sure to select the SDI
  (single-window) option.

** Install the =IPSUR= package
Launch =R= and type the following at the command prompt "\gt":

#+BEGIN_SRC R :eval no-export
install.packages("IPSUR", dependencies = TRUE)
#+END_SRC

** Load the =IPSUR= package 

Once =IPSUR= is downloaded and installed, it must be loaded into =R=.
Load the package with the =library= function:

#+BEGIN_SRC R :eval no-export
library(IPSUR)
#+END_SRC    

and finally launch your PDF viewer with

#+BEGIN_SRC R :eval no-export
read(IPSUR)
#+END_SRC

------------------------------------------------
