#    IPSUR: Introduction to Probability and Statistics Using R
#    Copyright (C) 2014 G. Jay Kerns
#
#    This file is part of IPSUR.
#
#    IPSUR is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    IPSUR is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with IPSUR.  If not, see <http://www.gnu.org/licenses/>.

#+TITLE:     IPSUR - Resources
#+AUTHOR:    G. Jay Kerns, Youngstown State University
#+EMAIL:     gkerns@ysu.edu
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:nil LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc email:t
#+INCLUDE: "header/header.org"

* Resources and Supplementary Materials

In Fall, 2010, I video-recorded my STAT 3743 course lectures as part
of a team initiative at YSU to develop a distance education program in
Statistics.  There are a lot of challenges associated with something
like that, particularly with respect to the integrity of the academic
climate.  It's a can of worms, to be sure. But I am coming to the
opinion that it just might be possible to make it work, and R may very
well be just the right tool for the task. We'll see.

In the meantime, the bottom line for you, the user, or the instructor,
is a fair amount of supplementary resources.  That means video
lectures (in a bunch of FREE formats), scanned lecture notes, course
outlines, source code for assessment materials such as labs, quizzes,
and exams, blank versions that a person can modify for other courses,
and all of it accompanies a FREE textbook, to boot.

The current place to find everything is here:   

#+BEGIN_CENTER
[[http://www.ysumathstat.org/faculty/kerns/video/]]
#+END_CENTER

If the location changes then I will post any updates on this page. Not
everything is finished; I will complete it as time permits. These
materials are a work in progress so please excuse any roughness around
the edges (it is astonishingly easy to forget to turn on that stupid
microphone).

------------------------------------------------
